/* Auto-generated by _build_speaking_scripts.py — do not edit by hand. */
/* Source: docs/scripts/{lr,ti}-practice-N-scripts.md */
window.TCK_SPEAKING_SCRIPTS = {
  "lr": {
    "1": {
      "theme": "Campus Library Tour Guide Training",
      "narrator": "You are a new student volunteer at the university library. Today is your first day of tour guide training. Listen to the trainer and repeat each sentence.",
      "items": [
        {
          "q": 1,
          "words": 5,
          "time": 8,
          "difficulty": 1,
          "text": "Welcome to the university library."
        },
        {
          "q": 2,
          "words": 10,
          "time": 8,
          "difficulty": 2,
          "text": "You can borrow up to ten books at a time."
        },
        {
          "q": 3,
          "words": 9,
          "time": 10,
          "difficulty": 2,
          "text": "The reference section is located on the second floor."
        },
        {
          "q": 4,
          "words": 10,
          "time": 10,
          "difficulty": 3,
          "text": "Please remember to return all materials before the due date."
        },
        {
          "q": 5,
          "words": 13,
          "time": 10,
          "difficulty": 3,
          "text": "If you need help finding a specific book, ask at the information desk."
        },
        {
          "q": 6,
          "words": 11,
          "time": 11,
          "difficulty": 4,
          "text": "The library offers free workshops on research skills every Wednesday afternoon."
        },
        {
          "q": 7,
          "words": 16,
          "time": 12,
          "difficulty": 5,
          "text": "We encourage all students to take advantage of our online database collection for their academic research."
        }
      ]
    },
    "10": {
      "theme": "Movie Theater Staff Training",
      "narrator": "You are working at a movie theater. Today is your first day of customer service training. Listen to the trainer and repeat each sentence.",
      "items": [
        {
          "q": 1,
          "words": 7,
          "time": 8,
          "difficulty": 1,
          "text": "Your movie starts in ten minutes."
        },
        {
          "q": 2,
          "words": 9,
          "time": 8,
          "difficulty": 2,
          "text": "Please keep your ticket until the film ends."
        },
        {
          "q": 3,
          "words": 12,
          "time": 10,
          "difficulty": 2,
          "text": "You can order popcorn and drinks at the concession stand over there."
        },
        {
          "q": 4,
          "words": 13,
          "time": 10,
          "difficulty": 3,
          "text": "I am sorry, but the seven o'clock show is completely sold out tonight."
        },
        {
          "q": 5,
          "words": 18,
          "time": 11,
          "difficulty": 3,
          "text": "Members of our loyalty program receive a free small popcorn with any ticket purchased before six in the evening."
        },
        {
          "q": 6,
          "words": 18,
          "time": 11,
          "difficulty": 4,
          "text": "If you arrive late for the film, please enter quietly and take the first available seat near the aisle."
        },
        {
          "q": 7,
          "words": 23,
          "time": 13,
          "difficulty": 5,
          "text": "We would like to remind all guests that recording any part of the film is strictly prohibited, and violators may be asked to leave."
        }
      ]
    },
    "2": {
      "theme": "University Campus Tour for New Students",
      "narrator": "You are a new student attending a campus tour at the university. Today is your first day on campus. Listen to the tour guide and repeat each sentence.",
      "items": [
        {
          "q": 1,
          "words": 5,
          "time": 8,
          "difficulty": 1,
          "text": "Welcome to our university campus."
        },
        {
          "q": 2,
          "words": 9,
          "time": 8,
          "difficulty": 2,
          "text": "The student center is right next to the cafeteria."
        },
        {
          "q": 3,
          "words": 11,
          "time": 9,
          "difficulty": 2,
          "text": "You can pick up your student ID at the registration office."
        },
        {
          "q": 4,
          "words": 13,
          "time": 10,
          "difficulty": 3,
          "text": "The gymnasium is open to all students from seven AM to ten PM."
        },
        {
          "q": 5,
          "words": 14,
          "time": 10,
          "difficulty": 3,
          "text": "If you have any questions, please visit the information desk on the first floor."
        },
        {
          "q": 6,
          "words": 13,
          "time": 11,
          "difficulty": 4,
          "text": "The computer lab on the third floor is available for printing and research."
        },
        {
          "q": 7,
          "words": 15,
          "time": 12,
          "difficulty": 5,
          "text": "We strongly recommend that new students attend the orientation session scheduled for next Monday morning."
        }
      ]
    },
    "3": {
      "theme": "Museum Audio Guide Training",
      "narrator": "You are a new volunteer at the city art museum. Today is your first day of audio guide training. Listen to the guide instructor and repeat each sentence.",
      "items": [
        {
          "q": 1,
          "words": 6,
          "time": 8,
          "difficulty": 1,
          "text": "Welcome to the city art museum."
        },
        {
          "q": 2,
          "words": 8,
          "time": 8,
          "difficulty": 2,
          "text": "Please do not touch the artwork on display."
        },
        {
          "q": 3,
          "words": 9,
          "time": 9,
          "difficulty": 2,
          "text": "This painting was created in the early nineteenth century."
        },
        {
          "q": 4,
          "words": 12,
          "time": 10,
          "difficulty": 3,
          "text": "The sculpture in the center of the room represents modern artistic expression."
        },
        {
          "q": 5,
          "words": 13,
          "time": 10,
          "difficulty": 3,
          "text": "Photography is allowed in this gallery, but please turn off your flash."
        },
        {
          "q": 6,
          "words": 13,
          "time": 11,
          "difficulty": 4,
          "text": "The special exhibition on the third floor features works by local contemporary artists."
        },
        {
          "q": 7,
          "words": 15,
          "time": 12,
          "difficulty": 5,
          "text": "We encourage all visitors to explore the interactive digital guide available on our museum app."
        }
      ]
    },
    "4": {
      "theme": "Airport Announcement Training",
      "narrator": "You are a new airport staff member starting your first day at the international terminal. Today is your orientation for making public announcements. Listen to the trainer and repeat each sentence.",
      "items": [
        {
          "q": 1,
          "words": 5,
          "time": 8,
          "difficulty": 1,
          "text": "Flight twenty-three is now boarding."
        },
        {
          "q": 2,
          "words": 8,
          "time": 8,
          "difficulty": 2,
          "text": "Please have your boarding pass and passport ready."
        },
        {
          "q": 3,
          "words": 9,
          "time": 9,
          "difficulty": 2,
          "text": "The departure gate has been changed to terminal B."
        },
        {
          "q": 4,
          "words": 11,
          "time": 10,
          "difficulty": 3,
          "text": "We apologize for the delay and thank you for your patience."
        },
        {
          "q": 5,
          "words": 11,
          "time": 10,
          "difficulty": 3,
          "text": "All passengers traveling to London should proceed to gate fourteen immediately."
        },
        {
          "q": 6,
          "words": 15,
          "time": 11,
          "difficulty": 4,
          "text": "For your safety, please keep your seatbelt fastened until the captain turns off the sign."
        },
        {
          "q": 7,
          "words": 16,
          "time": 12,
          "difficulty": 5,
          "text": "Due to severe weather conditions, all departures from this terminal have been temporarily suspended until further notice."
        }
      ]
    },
    "5": {
      "theme": "Hotel Front Desk Training",
      "narrator": "You are a new front desk receptionist at a luxury hotel. Today is your first day of guest service training. Listen to the trainer and repeat each sentence.",
      "items": [
        {
          "q": 1,
          "words": 5,
          "time": 8,
          "difficulty": 1,
          "text": "Welcome to the Grand Hotel."
        },
        {
          "q": 2,
          "words": 9,
          "time": 8,
          "difficulty": 2,
          "text": "May I have your name and reservation number, please?"
        },
        {
          "q": 3,
          "words": 12,
          "time": 10,
          "difficulty": 2,
          "text": "Your room is on the fifth floor with a view of the garden."
        },
        {
          "q": 4,
          "words": 13,
          "time": 10,
          "difficulty": 3,
          "text": "Breakfast is served in the main dining area from seven to ten each morning."
        },
        {
          "q": 5,
          "words": 14,
          "time": 10,
          "difficulty": 3,
          "text": "If you need extra towels or pillows, please contact the front desk at any time."
        },
        {
          "q": 6,
          "words": 15,
          "time": 11,
          "difficulty": 4,
          "text": "We also offer a complimentary airport shuttle that departs every thirty minutes from the lobby."
        },
        {
          "q": 7,
          "words": 20,
          "time": 12,
          "difficulty": 5,
          "text": "Should you have any concerns about your stay, please do not hesitate to let us know so we can assist you."
        }
      ]
    },
    "6": {
      "theme": "Zoo Volunteer Orientation",
      "narrator": "You are a new volunteer at the city zoo. Today is your orientation day. Listen to the trainer and repeat each sentence.",
      "items": [
        {
          "q": 1,
          "words": 5,
          "time": 8,
          "difficulty": 1,
          "text": "Welcome to the volunteer program."
        },
        {
          "q": 2,
          "words": 8,
          "time": 8,
          "difficulty": 2,
          "text": "Please wear your name badge at all times."
        },
        {
          "q": 3,
          "words": 12,
          "time": 10,
          "difficulty": 2,
          "text": "The animals are fed twice a day, in the morning and evening."
        },
        {
          "q": 4,
          "words": 10,
          "time": 10,
          "difficulty": 3,
          "text": "Never approach or touch the animals without a staff member present."
        },
        {
          "q": 5,
          "words": 13,
          "time": 10,
          "difficulty": 3,
          "text": "Your main responsibility will be helping visitors find their way around the park."
        },
        {
          "q": 6,
          "words": 15,
          "time": 11,
          "difficulty": 4,
          "text": "If you notice anything unusual about an animal's behavior, report it to the head keeper immediately."
        },
        {
          "q": 7,
          "words": 16,
          "time": 12,
          "difficulty": 5,
          "text": "We appreciate your dedication and hope you enjoy this rewarding experience working alongside our professional team."
        }
      ]
    },
    "7": {
      "theme": "Sports Center Staff Training",
      "narrator": "You are a new staff member at a sports center. Today is your first day of training. Listen to the trainer and repeat each sentence.",
      "items": [
        {
          "q": 1,
          "words": 5,
          "time": 8,
          "difficulty": 1,
          "text": "Welcome to the sports center."
        },
        {
          "q": 2,
          "words": 10,
          "time": 8,
          "difficulty": 2,
          "text": "All members must show their ID at the front desk."
        },
        {
          "q": 3,
          "words": 9,
          "time": 10,
          "difficulty": 2,
          "text": "The pool area closes at nine PM on weekdays."
        },
        {
          "q": 4,
          "words": 10,
          "time": 10,
          "difficulty": 3,
          "text": "Please report any broken equipment to a staff member immediately."
        },
        {
          "q": 5,
          "words": 13,
          "time": 10,
          "difficulty": 3,
          "text": "Group fitness classes are held in the main studio on the second floor."
        },
        {
          "q": 6,
          "words": 13,
          "time": 11,
          "difficulty": 4,
          "text": "Staff members should always greet visitors with a friendly attitude and offer assistance."
        },
        {
          "q": 7,
          "words": 18,
          "time": 12,
          "difficulty": 5,
          "text": "In the event of an emergency, guide all visitors to the nearest exit and contact the building manager right away."
        }
      ]
    },
    "8": {
      "theme": "Restaurant Service Training",
      "narrator": "You are a new server at a restaurant. Today is your first day of service training. Listen to the trainer and repeat each sentence.",
      "items": [
        {
          "q": 1,
          "words": 5,
          "time": 8,
          "difficulty": 1,
          "text": "Welcome to our restaurant today."
        },
        {
          "q": 2,
          "words": 9,
          "time": 8,
          "difficulty": 2,
          "text": "May I take your order whenever you are ready?"
        },
        {
          "q": 3,
          "words": 9,
          "time": 9,
          "difficulty": 2,
          "text": "Our chef recommends the grilled salmon with seasonal vegetables."
        },
        {
          "q": 4,
          "words": 13,
          "time": 10,
          "difficulty": 3,
          "text": "Please let me know if you have any food allergies or dietary restrictions."
        },
        {
          "q": 5,
          "words": 13,
          "time": 10,
          "difficulty": 3,
          "text": "I will bring your appetizers shortly while the main course is being prepared."
        },
        {
          "q": 6,
          "words": 15,
          "time": 11,
          "difficulty": 4,
          "text": "We sincerely apologize for the delay and would like to offer you a complimentary dessert."
        },
        {
          "q": 7,
          "words": 18,
          "time": 12,
          "difficulty": 5,
          "text": "If you enjoyed your dining experience today, we would greatly appreciate a positive review on our website."
        }
      ]
    },
    "9": {
      "theme": "Bookstore Customer Service Training",
      "narrator": "You are a new employee at the campus bookstore. Today is your first day of customer service training. Listen to the trainer and repeat each sentence.",
      "items": [
        {
          "q": 1,
          "words": 5,
          "time": 8,
          "difficulty": 1,
          "text": "Welcome to the campus bookstore."
        },
        {
          "q": 2,
          "words": 9,
          "time": 8,
          "difficulty": 2,
          "text": "How can I help you find what you need today?"
        },
        {
          "q": 3,
          "words": 10,
          "time": 10,
          "difficulty": 2,
          "text": "The textbook section is organized by department and course number."
        },
        {
          "q": 4,
          "words": 12,
          "time": 10,
          "difficulty": 3,
          "text": "We offer a ten percent discount on all used textbooks this week."
        },
        {
          "q": 5,
          "words": 16,
          "time": 11,
          "difficulty": 3,
          "text": "If the book you're looking for is out of stock, I can place a special order for you."
        },
        {
          "q": 6,
          "words": 16,
          "time": 11,
          "difficulty": 4,
          "text": "Please keep your receipt in case you need to return or exchange any items within thirty days."
        },
        {
          "q": 7,
          "words": 18,
          "time": 12,
          "difficulty": 5,
          "text": "We also carry a wide selection of university merchandise, school supplies, and graduation gifts on the second floor."
        }
      ]
    }
  },
  "ti": {
    "1": {
      "theme": "Technology and Daily Life",
      "narrator": "You have agreed to take part in a research study about technology and daily life. You will have a short online interview with a researcher. The researcher will ask you some questions.",
      "items": [
        {
          "q": 1,
          "text": "Thank you for participating in this study. I'm going to ask you a few questions about technology and daily life. How often do you use technology in your daily life?"
        },
        {
          "q": 2,
          "text": "That's interesting. Now, can you describe a time when technology helped you solve a problem?"
        },
        {
          "q": 3,
          "text": "I see. Some people believe that smartphones are essential tools that improve productivity. What do you think — do people spend too much time on their smartphones? Why or why not?"
        },
        {
          "q": 4,
          "text": "That's a great point. Some people argue that technology actually brings people closer together through social media and video calls. Do you agree or disagree that technology is making us less social?"
        }
      ]
    },
    "10": {
      "theme": "Travel and Vacation",
      "narrator": "You have agreed to take part in a research study about travel and vacation. You will have a short online interview with a researcher. The researcher will ask you some questions.",
      "items": [
        {
          "q": 1,
          "text": "Thank you for joining this study. I'd like to ask you about travel and vacation. Where did you go on your most recent trip, and what did you do there?"
        },
        {
          "q": 2,
          "text": "That sounds like a wonderful trip. Thank you for sharing that. Describe a time when something unexpected happened during a trip. How did you handle it?"
        },
        {
          "q": 3,
          "text": "I see. That must have been quite an experience. Some people think that traveling with others is always better than traveling alone because it's safer and more enjoyable. Do you prefer traveling alone or with other people? Why?"
        },
        {
          "q": 4,
          "text": "That's a really good point. Some people argue that international travel broadens your perspective more than reading books or watching documentaries. Do you agree or disagree with this view? Why do you think so?"
        }
      ]
    },
    "2": {
      "theme": "Education and Learning Styles",
      "narrator": "You have agreed to take part in a research study about education and learning styles. You will have a short online interview with a researcher. The researcher will ask you some questions.",
      "items": [
        {
          "q": 1,
          "text": "Thank you for participating in this study. I'm going to ask you a few questions about education and learning. What subjects are you currently studying, and which one do you find most interesting?"
        },
        {
          "q": 2,
          "text": "That's interesting. Now, can you describe a study method that has worked well for you in the past?"
        },
        {
          "q": 3,
          "text": "I see. Some people believe that online classes offer more flexibility and are just as effective as in-person classes. What do you think — are online classes as effective as in-person classes? Why or why not?"
        },
        {
          "q": 4,
          "text": "That's a great point. Some people argue that a structured curriculum ensures all students receive a well-rounded education. Do you agree or disagree that students should be allowed to choose what they study?"
        }
      ]
    },
    "3": {
      "theme": "Travel and Cultural Exchange",
      "narrator": "You have agreed to take part in a research study about travel and cultural exchange. You will have a short online interview with a researcher. The researcher will ask you some questions.",
      "items": [
        {
          "q": 1,
          "text": "Thank you for participating in this study. I'm going to ask you a few questions about travel and cultural exchange. Have you ever traveled to a foreign country? If so, where did you go?"
        },
        {
          "q": 2,
          "text": "That's interesting. Now, can you describe a memorable experience you had while learning about a different culture?"
        },
        {
          "q": 3,
          "text": "I see. Some people believe that you can learn just as much about other cultures through books and the internet without leaving your home country. What do you think — is studying abroad more beneficial than studying in your home country? Why or why not?"
        },
        {
          "q": 4,
          "text": "That's a great point. Some people argue that globalization actually helps preserve cultures by increasing awareness and appreciation worldwide. Do you agree or disagree that globalization is causing local cultures to disappear?"
        }
      ]
    },
    "4": {
      "theme": "Health and Fitness",
      "narrator": "You have agreed to take part in a research study about health and fitness. You will have a short online interview with a researcher. The researcher will ask you some questions.",
      "items": [
        {
          "q": 1,
          "text": "Thank you for participating in this study. I'm going to ask you a few questions about health and fitness. How often do you exercise or do physical activities?"
        },
        {
          "q": 2,
          "text": "That's interesting. Now, tell me about a time when you tried to change a health habit. What happened?"
        },
        {
          "q": 3,
          "text": "I see. Some people believe that academic subjects should always take priority over physical education in schools. What do you think — should schools require students to take physical education classes every day? Why or why not?"
        },
        {
          "q": 4,
          "text": "That's a great point. Some people argue that health choices are a personal responsibility and governments should not interfere. Do you agree or disagree that governments should do more to promote healthy lifestyles among citizens?"
        }
      ]
    },
    "5": {
      "theme": "Work and Career Goals",
      "narrator": "You have agreed to take part in a research study about work and career goals. You will have a short online interview with a researcher. The researcher will ask you some questions.",
      "items": [
        {
          "q": 1,
          "text": "Thank you for participating in this study. I'm going to ask you a few questions about work and career goals. What kind of job or career are you currently interested in?"
        },
        {
          "q": 2,
          "text": "That's interesting. Now, can you describe a work experience or project that taught you an important lesson?"
        },
        {
          "q": 3,
          "text": "I see. Some people believe that financial stability should be the top priority when choosing a career. What do you think — is it better to choose a job you love or one that pays well? Why?"
        },
        {
          "q": 4,
          "text": "That's a great point. Some people argue that automation and AI will create more jobs than they eliminate. Do you agree or disagree? How do you think the job market will change in the next ten years due to technology?"
        }
      ]
    },
    "6": {
      "theme": "Environment and Nature",
      "narrator": "You have agreed to take part in a research study about the environment and nature. You will have a short online interview with a researcher. The researcher will ask you some questions.",
      "items": [
        {
          "q": 1,
          "text": "Thank you for joining this study. I'd like to ask you about the environment and the natural world. What is the biggest environmental problem in your country?"
        },
        {
          "q": 2,
          "text": "That's interesting. Thank you for sharing that. Can you describe a time when you did something to help the environment?"
        },
        {
          "q": 3,
          "text": "Thank you for that example. Some people believe that environmental protection is mainly the responsibility of governments and large corporations, not individuals. Do you think individuals can make a real difference in protecting the environment, or is it mainly the responsibility of governments and companies?"
        },
        {
          "q": 4,
          "text": "I see. That's a thoughtful perspective. Some people argue that economic growth and environmental protection cannot go hand in hand — that one must be sacrificed for the other. What is your view on this? Can a country pursue economic development while also protecting the environment?"
        }
      ]
    },
    "7": {
      "theme": "Media and Entertainment",
      "narrator": "You have agreed to take part in a research study about media and entertainment. You will have a short online interview with a researcher. The researcher will ask you some questions.",
      "items": [
        {
          "q": 1,
          "text": "Thank you for joining this study. I'd like to ask you about media and entertainment. What types of media do you consume most often, such as TV shows, movies, podcasts, or social media?"
        },
        {
          "q": 2,
          "text": "That's interesting. Thank you for sharing that. Can you describe a movie or TV show that left a strong impression on you? What made it memorable?"
        },
        {
          "q": 3,
          "text": "That sounds like a great experience. Some people think that traditional television still offers a better viewing experience than streaming services. Do you think streaming services are better than traditional television? Why or why not?"
        },
        {
          "q": 4,
          "text": "I see. That's an interesting point. Some people argue that social media has a negative influence on how we consume news, making it harder to distinguish facts from opinions. Do you agree or disagree with that view? Why?"
        }
      ]
    },
    "8": {
      "theme": "Food and Cooking",
      "narrator": "You have agreed to take part in a research study about food and cooking. You will have a short online interview with a researcher. The researcher will ask you some questions.",
      "items": [
        {
          "q": 1,
          "text": "Thank you for joining this study. I'd like to ask you about food and cooking. What is your favorite type of food, and how often do you eat it?"
        },
        {
          "q": 2,
          "text": "That sounds delicious. Thank you for sharing that. Tell me about a time when you tried cooking a new dish. How did it turn out?"
        },
        {
          "q": 3,
          "text": "That's a great story. Some people believe that eating out at restaurants is just as healthy as cooking at home, especially with so many healthy options available now. Do you think home-cooked meals are healthier than eating out? Why or why not?"
        },
        {
          "q": 4,
          "text": "I see. That's an interesting perspective. Some people say that traditional cooking skills are disappearing because of modern convenience foods and delivery services. Do you agree or disagree with this view? What do you think the future of home cooking looks like?"
        }
      ]
    },
    "9": {
      "theme": "Friendship and Social Life",
      "narrator": "You have agreed to take part in a research study about friendship and social life. You will have a short online interview with a researcher. The researcher will ask you some questions.",
      "items": [
        {
          "q": 1,
          "text": "Thank you for joining this study. I'd like to ask you about friendship and your social life. How do you usually spend time with your friends?"
        },
        {
          "q": 2,
          "text": "That sounds like a lot of fun. Thank you for sharing that. Tell me about a time when a friend helped you through a difficult situation."
        },
        {
          "q": 3,
          "text": "That's a wonderful example of friendship. Some people believe that having a large social circle with many casual friends is more beneficial than having just a few close ones. Do you think it is better to have a few close friends or many casual friends? Why?"
        },
        {
          "q": 4,
          "text": "I see. That's a thoughtful answer. Some people say that social media has made it harder to maintain real friendships because online interactions replace face-to-face connections. Do you agree or disagree with this view? How has technology affected your own friendships?"
        }
      ]
    }
  }
};
