/* Auto-generated by tools/extract-tips.py — do not edit by hand. */
window.TCK_TIPS = {
  "reading": [
    {
      "titleJp": "品詞を特定してから埋める",
      "titleEn": "Identify the part of speech first",
      "bodyJp": "冠詞＋空欄 → 名詞／主語＋空欄 → 動詞／be 動詞＋空欄 → 形容詞・過去分詞／空欄＋名詞 → 形容詞",
      "bodyEn": "Article + blank → noun · Subject + blank → verb · Be + blank → adj/participle · Blank + noun → adj",
      "task": "CTW",
      "taskJp": "CTW"
    },
    {
      "titleJp": "頻出パターンを暗記する",
      "titleEn": "Memorize recurring patterns",
      "bodyJp": "however, therefore, although, particularly, significant, demonstrate, evidence … 見たら即座に埋められるように。",
      "bodyEn": "however, therefore, although, particularly, significant, demonstrate, evidence — recognize them instantly.",
      "task": "CTW",
      "taskJp": "CTW"
    },
    {
      "titleJp": "推測でも必ず埋めるAlways fill the blank",
      "titleEn": "Always fill the blank",
      "bodyJp": "正解 → 得点／不正解 → 0 点／空欄 → 0 点。推測しないと損。",
      "bodyEn": "Correct → points · Wrong → 0 · Blank → 0. Guessing costs nothing.",
      "task": "CTW",
      "taskJp": "CTW"
    },
    {
      "titleJp": "Intro と Conclusion を先に読む",
      "titleEn": "Read intro and conclusion first",
      "bodyJp": "最初と最後の文でトピックと流れを掴む。推測精度が上がる。",
      "bodyEn": "The opening and closing sentences tell you the topic and flow — better context, better guesses.",
      "task": "CTW",
      "taskJp": "CTW"
    },
    {
      "titleJp": "推測でも必ず埋める",
      "titleEn": "Always fill the blank",
      "bodyJp": "正解 → 得点 / 不正解 → 0点 / 空欄 → 0点",
      "bodyEn": "Correct → points / Wrong → 0 / Blank → 0",
      "task": "CTW",
      "taskJp": "CTW"
    },
    {
      "titleJp": "INTROとCONCLUSIONを先に読む",
      "titleEn": "Read intro and conclusion first",
      "bodyJp": "最初と最後の文を先に読めば、トピックと流れが掴める。空欄の推測精度が上がる！",
      "bodyEn": "Reading the opening and closing sentences first reveals the topic and flow — better context, better guesses on the blanks.",
      "task": "CTW",
      "taskJp": "CTW"
    },
    {
      "titleJp": "冒頭のキーワードから目的を特定する",
      "titleEn": "Identify the purpose from opening keywords",
      "bodyJp": "最初の1〜2文に文章の目的が示されている。次のパターンを覚えておこう。通知: We are pleased to inform... / We would like to inform you...依頼: Could you... / I would appreciate if...確認: I'm writing to confirm...謝罪: I apologize for... / Unfortunately...",
      "bodyEn": "The first 1-2 sentences reveal the purpose of the text. Learn the patterns:Notification: We are pleased to inform... / We would like to inform you...Request: Could you... / I would appreciate if...Confirmation: I'm writing to confirm...Apology: I apologize for... / Unfortunately...",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "NOT/EXCEPT問題は消去法で",
      "titleEn": "NOT/EXCEPT: Use elimination",
      "bodyJp": "手順:1. 設問の NOT/EXCEPT を意識する（CBTなので画面に印は付けられないが、頭の中で必ず確認）2. 各選択肢をパッセージと一つずつ照らし合わせる3. パッセージに書かれている3つの選択肢を消去候補にする。残った1つが正解。",
      "bodyEn": "Steps:1. Note the NOT/EXCEPT in the question (you can't mark the screen — fix it in your head)2. Check each option against the passage one by one3. Rule out the 3 options that ARE mentioned in the passage. The remaining one is the answer.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "推論問題は本文から離れない",
      "titleEn": "Inference questions: stick to the text",
      "bodyJp": "推論問題では、答えはパッセージの情報から論理的に導かれるものでなければならない。自分の知識や思い込みを混ぜないこと。",
      "bodyEn": "For inference questions, the answer must be logically supported by information in the passage. Do not mix in your own knowledge or assumptions.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "NOT/EXCEPT問題は各選択肢を検証する",
      "titleEn": "For NOT/EXCEPT, verify each option",
      "bodyJp": "「次のうち〜でないものはどれか（all of the following EXCEPT）」問題では、4つのうち3つはパッセージに含まれ、1つは含まれない。各選択肢を本文と照合し、仲間外れを見つけるのが正解。",
      "bodyEn": "In \"all of the following EXCEPT\" questions, three options are in the passage and one is not. Check each option against the text — the odd one out is your answer.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "結果からの推論",
      "titleEn": "Inference from consequences",
      "bodyJp": "通知には締切が含まれていることが多い。締切が明示されている場合、それを過ぎた後に何が起きるかを考えよう — それが推論問題の典型的な狙いどころ。",
      "bodyEn": "Notices often include deadlines. If a deadline is stated, think about what happens after it passes — that is usually what an inference question targets.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "SMSは会話の流れを追う",
      "titleEn": "SMS: follow the conversation flow",
      "bodyJp": "テキストメッセージは展開が速い。各吹き出しを順に読み、誰が同意し、誰が反対し、最終的にどんな計画になったかを記録する。最後の吹き出しで計画が確定することが多い。",
      "bodyEn": "Text messages move fast. Read each bubble in order and note who agrees, who disagrees, and what plan is made at the end. The final bubbles usually settle the plan.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "冒頭のキーワードから目的を特定する",
      "titleEn": "Identify the purpose from opening keywords",
      "bodyJp": "最初の1〜2文に文章の目的が示されている。次のパターンを覚えておこう。 通知: We are pleased to inform... / We would like to inform you... 依頼: Could you... / I would appreciate if... 確認: I'm writing to confirm... 謝罪: I apologize for... / Unfortunately...",
      "bodyEn": "The first 1-2 sentences reveal the purpose of the text. Learn the patterns: Notification: We are pleased to inform... / We would like to inform you... Request: Could you... / I would appreciate if... Confirmation: I'm writing to confirm... Apology: I apologize for... / Unfortunately...",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "NOT/EXCEPT問題は消去法で",
      "titleEn": "NOT/EXCEPT: Use elimination",
      "bodyJp": "手順: 1. 設問の NOT/EXCEPT を意識する（CBTなので画面に印は付けられないが、頭の中で必ず確認） 2. 各選択肢をパッセージと一つずつ照らし合わせる 3. パッセージに書かれている3つの選択肢を消去候補にする。残った1つが正解。",
      "bodyEn": "Steps: 1. Note the NOT/EXCEPT in the question (you can't mark the screen — fix it in your head) 2. Check each option against the passage one by one 3. Rule out the 3 options that ARE mentioned in the passage. The remaining one is the answer.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "推論問題は本文から離れない",
      "titleEn": "Inference questions: stick to the text",
      "bodyJp": "推論問題では、答えはパッセージの情報から論理的に導かれるものでなければならない。自分の知識や思い込みを混ぜないこと。",
      "bodyEn": "For inference questions, the answer must be logically supported by information in the passage. Do not mix in your own knowledge or assumptions.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "SNS投稿は画像でなくキャプションを読む",
      "titleEn": "Social media posts: read the caption, not just the image",
      "bodyJp": "SNS投稿は短い文章に多くの情報が詰め込まれている。主目的は最初の1〜2文に書かれていることが多く、具体的な指示（持ち物、連絡先）は後半に登場する。ハッシュタグや絵文字は装飾なので無視し、本文の段落に集中しよう。",
      "bodyEn": "Social media posts pack a lot of information into a short text. The main purpose is usually in the first 1-2 sentences, while specific instructions (what to bring, who to contact) appear later. Hashtags and emoji are decorative — focus on the body paragraphs.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "スケジュール表は行を時刻と照合する",
      "titleEn": "Schedules: match the event to the time column",
      "bodyJp": "スケジュール形式のパッセージでは、視線を横方向に動かすこと：行を見つけ、時刻を確認し、イベントを読む。EXCEPT問題では、有料項目や別途チケットが必要な項目を冒頭の説明や脚注から拾う。",
      "bodyEn": "For schedule passages, your finger should move horizontally: find the row, check the time, then read the event. For EXCEPT questions, use the intro or footnotes to catch items that cost extra or require separate tickets.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "推論問題は根拠となる1文を探す",
      "titleEn": "Inference: find the single supporting sentence",
      "bodyJp": "正解の推論は1つの具体的な文によって論理的に裏付けられる。根拠の文を指さして示せないなら、それはおそらく不正解の選択肢。",
      "bodyEn": "The correct inference answer is logically supported by one specific sentence. If you can't point to a sentence that supports it, it's probably a distractor.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "テキストメッセージは「誰が何を言ったか」を追う",
      "titleEn": "Text messages: track who says what",
      "bodyJp": "SMSのやり取りでは、原因・条件・約束が話者ごとに分かれて書かれる。回答する前に、どの吹き出しに該当の情報があるかを特定すること。自分のメッセージと相手のメッセージを混同しないように。",
      "bodyEn": "In SMS threads, causes, conditions, and promises are spread across speakers. Before answering, identify which bubble contains the specific fact — do not confuse your own message with the other person's.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "EXCEPT問題は「書かれているもの」を消去する",
      "titleEn": "EXCEPT questions: eliminate what IS stated",
      "bodyJp": "EXCEPT や NOT 問題では、各選択肢をパッセージ内で探し、登場するものを消去する。見つからなかった1つが正解。",
      "bodyEn": "For EXCEPT or NOT questions, find each option in the passage and cross it off if it appears. The one you cannot find is the answer.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "引用文は推論のヒントを示す",
      "titleEn": "Quoted speech signals inference clues",
      "bodyJp": "ニュース記事で誰かの発言が直接引用されているとき、その引用文に暗示された主張が込められていることが多い。選択肢を見る前に、話者の論点を自分の言葉で言い換えてみよう。",
      "bodyEn": "When a news article quotes someone directly, the quote usually carries the implied argument. Paraphrase the speaker's point in your own words before scanning options.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "フォームは事実を表として読む",
      "titleEn": "Read forms like a table of facts",
      "bodyJp": "フォームは1行に1つの事実を記載する。設問のキーワードを左側のラベルと照合し、その行の値だけを読む。フォーム問題のほとんどは直接的な事実問題。",
      "bodyEn": "Forms store one fact per row. Match the question's key phrase to the left-hand label and read only that row's value. Most form questions are directly factual.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "小さな注記から含意を読み取る",
      "titleEn": "Use small notes for what they imply",
      "bodyJp": "フォームには小さな Note や脚注が含まれていることが多い。これらが推論問題の根拠となる — 注記は何が許可されていて何が許可されていないかを示す。",
      "bodyEn": "Forms often include a small Note or footnote. These are the source of inference questions — the note tells you what is and is not permitted.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "レシート問題は合計欄を慎重に読む",
      "titleEn": "Receipts: read the totals block carefully",
      "bodyJp": "レシート問題は通常、割引・税金・手数料がどう適用されたかを問う。金額の数字だけでなく、隣のラベルを必ず確認すること。",
      "bodyEn": "A receipt question is usually about how a discount, tax, or fee was applied. Look at the label next to the amount, not just the number.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "グループチャットでは「誰が何を言ったか」を追う",
      "titleEn": "Track who says what in a group chat",
      "bodyJp": "グループの会話では、各メッセージが特定の発信者と結び付いている。設問は 特定の人物 が何をするかを問うことが多い。発信者の名前を先に読み、その人の発言を特定する — メンバー同士のタスクを混同しないように。",
      "bodyEn": "In a group conversation, each message is tied to a specific sender. Questions often ask what a particular person will do. Read the sender's name first, then locate their statement — don't mix up tasks between members.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "推論問題は「実際に書かれていること」に近づく",
      "titleEn": "Inference: stay close to what is actually said",
      "bodyJp": "推論は本文によって論理的に裏付けられる必要がある。Sofia は \"I'm swamped with my chem lab this week.\" と言っている。これは「彼女が他の授業で忙しい」という考えを直接支持する。本文が許す範囲を超えた大きな結論（「手伝いたくない」など）に飛びつかないこと。",
      "bodyEn": "An inference must be logically supported by the text. Sofia says \"I'm swamped with my chem lab this week.\" This directly supports the idea that she is busy with another subject. Don't jump to bigger conclusions (like \"she doesn't want to help\") that go beyond what the text warrants.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "広告では割引の条件に注意",
      "titleEn": "Advertisements: watch conditions on discounts",
      "bodyJp": "広告のパッセージには条件が異なる複数のオファー（早期割引、学生割引、会員割引など）が含まれることが多い。設問はオファーを正確な条件と一致させられるかを問う。CBTでは画面に書き込めないため、最初に読むときに各割引の締切や条件を頭の中で「ラベル付け」して整理しよう（例：「早期 = 3/15まで」「学生 = ID必須」）。",
      "bodyEn": "Ad passages usually include multiple offers with different conditions (early bird, student discount, membership, etc.). Questions often test whether you can match the offer to its exact condition. Since you can't annotate the screen on a CBT, mentally label each offer with its deadline or requirement on your first read (e.g., \"early bird = by 3/15\", \"student = ID required\").",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "NOT/EXCEPT問題は記載のあるものを消去する",
      "titleEn": "NOT/EXCEPT: eliminate what is mentioned",
      "bodyJp": "手順: 1. 設問の NOT/EXCEPT を意識する（CBTなので画面に印は付けられないが、頭の中で必ず確認） 2. 各選択肢をパッセージと一つずつ照らし合わせる 3. 記載のある3つの選択肢を消去候補にする。残った1つが正解。",
      "bodyEn": "Steps: 1. Note the NOT/EXCEPT in the question (you can't mark the screen — fix it in your head) 2. Check each option against the passage one by one 3. Rule out the 3 options that ARE mentioned. The remaining one is the answer.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "スケジュールは見出しと脚注を読む",
      "titleEn": "Schedules: read the headers and the footnotes",
      "bodyJp": "スケジュールには2層の情報がある：表本体（曜日、時刻、名前）と、その上下の注記（ルールと例外）。設問は注記を狙うことが多い。",
      "bodyEn": "A schedule has two layers of information: the table itself (days, hours, names) and the notes above or below (rules and exceptions). Questions often target the notes.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "メニューは説明文の中のオプション表現に注目",
      "titleEn": "Menus: scan the descriptions for optional phrases",
      "bodyJp": "メニューでよく見るオプション表現： Add X for $Y / available on request / choose from ... EXCEPT問題で「提供されていない選択肢」を問われた場合、もっともらしいがメニューに書かれていない選択肢が罠。",
      "bodyEn": "Common option signals on a menu: Add X for $Y / available on request / choose from ... If an EXCEPT question asks which option is not offered, an answer that sounds reasonable but is never written on the menu is the trap you are looking for.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "推論 = 「必ず真であること」、「真かもしれないこと」ではない",
      "titleEn": "Inference = what must be true, not what might be true",
      "bodyJp": "正しい推論は本文によって直接裏付けられる。外部知識や新たな前提を加えなければ成立しないなら、それはおそらく不正解の選択肢。",
      "bodyEn": "A correct inference is directly supported by the text. If you have to add outside knowledge or make a new assumption, it is probably a distractor.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "ニュース記事は事実と背景を分ける",
      "titleEn": "News articles: separate facts from background",
      "bodyJp": "ニュース記事は中心となる出来事（「誰が、何を、いつ、どこで」）から始まる。後続の段落では理由、引用、今後の予定が追加される。事実問題では、記事全体を読み直すのではなく、そのサブトピックを扱う特定の段落を特定すること。",
      "bodyEn": "News articles open with the core event (\"who did what, when, where\"). Later paragraphs add reasons, quotes, and future plans. For factual questions, locate the specific paragraph that deals with that sub-topic rather than re-reading the whole article.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "推論問題は未来形の文を確認する",
      "titleEn": "Inference: check the future-tense sentences",
      "bodyJp": "記事の最後が「plans to」「will hold」「goal of」のような文で締められている場合、その一文が推論問題の根拠になることが多い。書き手は次に何が起こるかを伝えており、それを使って組織やイベントについての結論を導くことができる。",
      "bodyEn": "When an article ends with a sentence about \"plans to,\" \"will hold,\" or \"goal of,\" that line is often the basis for inference questions. The writer is telling you what comes next — use that to draw conclusions about the organization or the event.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "SNS投稿はカジュアルな口調を慎重に読む",
      "titleEn": "Social media posts: read the informal tone carefully",
      "bodyJp": "SNSの投稿は短くカジュアルだが、すべての表現が情報を含んでいる。「Honestly, my Portuguese is still rough, but the staff keep switching to English to help me out」は困難と肯定的な反応の両方を示している。推論問題では「書き手の言葉遣いはどんな態度や状況を明らかにしているか？」と問うこと。",
      "bodyEn": "Social posts are short and casual, but every phrase carries information. \"Honestly, my Portuguese is still rough, but the staff keep switching to English to help me out\" shows both a difficulty and a positive response. For inference, ask: \"What attitude or situation does the writer's word choice reveal?\"",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "学生から教授へのメールは「依頼の一文」を探す",
      "titleEn": "Student-to-professor emails: find the single \"ask\"",
      "bodyJp": "丁寧な依頼メールは、本題に入る前に挨拶や背景が長く書かれていることが多い。次のような表現を探そう： 依頼: I was hoping you might... / Would you be willing to... / I would appreciate it if you could... 背景（目的の設問では飛ばす）: Since I completed... / As you may recall...",
      "bodyEn": "Polite request emails often open with pleasantries and background before getting to the point. Look for phrases like: The ask: I was hoping you might... / Would you be willing to... / I would appreciate it if you could... Background (skip for purpose Qs): Since I completed... / As you may recall...",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "フォームはセクション見出しでスキャンする",
      "titleEn": "Reading forms: scan by section headers",
      "bodyJp": "フォームはラベル付きのセクション（Applicant Info、Preferences など）で構成されている。上から順に読まず、設問で名指しされたセクションへ直接ジャンプする。",
      "bodyEn": "Forms are organized into labeled sections (Applicant Info, Preferences, etc.). Don't read top-to-bottom — jump to the section named in the question.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "NOT / EXCEPT問題：すべての選択肢を本文と照合",
      "titleEn": "NOT / EXCEPT questions: check every option against the text",
      "bodyJp": "否定形の事実問題では、4つの選択肢のうち3つがパッセージに記載されている。記載されていない1つを見つけるのが仕事。",
      "bodyEn": "For negative factual questions, three of the four options ARE mentioned in the passage. Your job is to find the one that is NOT there.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "チェックボックスからの推論：ラベルとチェックを組み合わせる",
      "titleEn": "Inference from checkboxes: combine the label with the check",
      "bodyJp": "チェックボックスは2つの情報を持つ：記載内容と選択されているかどうか。推論は、近くにある条件付きの注記（例：「住居手当が必要」）と組み合わせることで導かれる。",
      "bodyEn": "A checkbox carries two pieces of info: the statement and whether it's selected. The inference usually comes from pairing them with nearby qualifying text (e.g., \"housing stipend required\").",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "正解は常にパッセージの言い換え",
      "titleEn": "Correct answers are always paraphrases",
      "bodyJp": "正解は本文を別の言葉で言い直したもの。パッセージと同じ単語をそのまま使った選択肢は罠であることが多い。",
      "bodyEn": "Correct answers restate the passage in different words. Be suspicious of options that copy exact wording — they are often traps.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "パッセージの構造を把握する",
      "titleEn": "Understand passage structure",
      "bodyJp": "最初の文 → トピック・主張、中盤 → 詳細・例・データ、最後の文 → 結論・まとめ。主旨問題は最初と最後の文だけで解けることが多い。",
      "bodyEn": "First sentence → topic / main claim · Middle → details, examples, data · Last sentence → conclusion. Main-Idea questions can often be solved from the first and last sentences alone.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "推論は本文の情報だけから導く",
      "titleEn": "Inference must come from the text only",
      "bodyJp": "推論問題では、答えはパッセージの情報から論理的に導かれるものでなければならない。自分の知識や思い込みを混ぜないこと。",
      "bodyEn": "An inference must be logically supported by the passage. Do not mix in your own knowledge or assumptions.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "主旨問題は最初と最後の文がカギ",
      "titleEn": "Main Idea: first + last sentences are key",
      "bodyJp": "主旨問題は最初と最後の文を先に読むだけで答えられることが多い。中盤の細部に振り回されない。",
      "bodyEn": "Main-Idea questions can usually be answered just by reading the first and last sentences. Don't get pulled into middle-paragraph details.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "重要ポイント",
      "titleEn": "Key Takeaways",
      "bodyJp": "1. 正解は常にパッセージの言い換えである。 パッセージと同じ単語を使った選択肢は罠であることが多い。 2. 推論問題では、根拠はパッセージ内のみ。 自分の知識や意見を持ち込まないこと。 3. 主旨 = 最初の文 + 最後の文。 段落中央の細部に引き込まれないように。 4. 文脈中の語彙：代入して確認。 各選択肢で語を置き換え、最も自然に読めるものを選ぶ。",
      "bodyEn": "1. Correct answers are always paraphrases of the passage. Options using the same words as the passage are often traps. 2. For inference questions, only the passage counts as evidence. Do not mix in your own knowledge or opinions. 3. Main Idea = first sentence + last sentence. Do not get pulled into middle-paragraph details. 4. Vocabulary in Context: substitute and check. Replace the word with each option and see which one reads most naturally.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "文脈中の語彙：代入して確認",
      "titleEn": "Vocabulary in Context: substitute and check",
      "bodyJp": "対象語に各選択肢を代入して、文の中で最も自然に読めるものを選ぶ。",
      "bodyEn": "Replace the target word with each option and pick the one that reads most naturally in the sentence.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "修辞目的問題：「著者は何を言おうとしているか」を問う",
      "titleEn": "Rhetorical Purpose: ask \"what point is the author making?\"",
      "bodyJp": "修辞目的問題は「なぜそれを言ったか」を問う。詳細そのものではなく、その詳細が支える主張を考える。",
      "bodyEn": "Purpose questions ask why the author mentioned something, not what it means. Look for the claim the detail supports.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "正解は常にパッセージの言い換え",
      "titleEn": "Correct answers are always paraphrases",
      "bodyJp": "正解は本文を別の言葉で言い直したもの。同じ単語をそのまま使った選択肢には注意。",
      "bodyEn": "Correct answers restate the passage in different words. Watch out for options that reuse the exact wording.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "語彙問題：まず品詞を特定する",
      "titleEn": "Vocabulary: identify the part of speech first",
      "bodyJp": "選択肢を見る前に、対象語が名詞・動詞・形容詞・副詞のどれかを判断する。次に各選択肢を代入して文法・意味の両方が合うものを選ぶ。",
      "bodyEn": "Before looking at options, decide if the target word is a noun, verb, adjective, or adverb. Then substitute each option and pick the one that fits both grammatically and logically.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "修辞目的問題：前後の文を読む",
      "titleEn": "Rhetorical Purpose: read the sentence before and after",
      "bodyJp": "「なぜ著者はXに言及したか」と問われたら、Xの直前の文を読む。著者は主張を述べてからXを例や根拠として挙げているのが典型パターン。",
      "bodyEn": "When asked \"Why does the author mention X?\", check the sentence immediately before X — the author usually states a claim and then offers X as the example or evidence.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "難問は消去法で",
      "titleEn": "Use elimination for difficult questions",
      "bodyJp": "迷ったら、極端な語（always, never, only, all, none）を含む選択肢や本文に書かれていない情報を含む選択肢を消去する。正解は穏やかな表現を使うことが多い。",
      "bodyEn": "When unsure, eliminate options with extreme words (always, never, only, all, none) or claims not in the passage. Correct answers tend to use moderate language.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "修辞目的問題：「what」ではなく「why」を問う",
      "titleEn": "Rhetorical Purpose: ask \"why,\" not \"what\"",
      "bodyJp": "目的問題は「著者がなぜそれに言及したか」を問う。意味そのものを聞いているのではない。直前の文に主張があり、その例として詳細が出てくるのが定番。",
      "bodyEn": "Purpose questions ask why the author mentions something, not what it means. The previous sentence usually states the claim that the detail illustrates.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "文挿入問題：ディスコースマーカーを手がかりに",
      "titleEn": "Sentence Insertion: use discourse markers as clues",
      "bodyJp": "挿入文の冒頭の「Furthermore」「However」「For example」「In contrast」などが、前後の文との論理関係を示している。マーカーが示す関係に合う位置を選ぶ。",
      "bodyEn": "Words like \"Furthermore,\" \"However,\" \"For example,\" or \"In contrast\" at the start of an inserted sentence signal its logical link to surrounding text. Match the marker to the right relationship.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "修辞目的問題：「なぜ著者はこれを含めたか」を問う",
      "titleEn": "Rhetorical Purpose: ask \"why did the author include this?\"",
      "bodyJp": "目的問題は詳細の中身ではなく、その役割を問う。「著者はこれで何を言いたかったのか」と自問する。答えは段落の主張に詳細を結びつけるもの。",
      "bodyEn": "Purpose questions ask about the function of a detail, not its content. Ask: \"What point is the author making by including this?\" The answer connects the detail to the paragraph's main claim.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "推論：各進歩 = 新たな能力",
      "titleEn": "Inference: each advance = new capability",
      "bodyJp": "パッセージが一連の発展を述べているとき、パターンを探す。各新技術が新しい何かを明らかにしていれば、進歩 = 拡張された能力と推論できる。",
      "bodyEn": "When a passage describes a series of advances, look for the pattern. If each new technology reveals something new, you can infer that progress means expanded capability.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "修辞目的問題：「なぜ著者はこれを含めたか」を問う",
      "titleEn": "Rhetorical purpose: ask \"why did the author include this?\"",
      "bodyJp": "目的問題は詳細の中身ではなく、その役割を問う。詳細の直前の文に、その例が支える主張が書かれているのが典型パターン。",
      "bodyEn": "Purpose questions ask about the function of a detail, not the detail itself. The sentence right before the detail usually states the claim that the example supports.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "修辞目的問題：「なぜ著者はこれを含めたか」を問う",
      "titleEn": "Rhetorical Purpose: ask \"Why did the author include this?\"",
      "bodyJp": "具体例を見たら自問する：著者が支持しようとした一般的な主張は何か？目的問題の正解は例そのものではなく、より大きな主張について述べている。",
      "bodyEn": "When you see a specific example, ask: what general point was the author trying to support? The answer to a purpose question is never about the example itself — it's about the larger claim.",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "文挿入問題：指示参照を追う",
      "titleEn": "Sentence Insertion: follow the referents",
      "bodyJp": "ディスコースマーカーがない場合は、代名詞参照と語彙のエコー（言い換え）を追跡し、新しい文を直前の特定の文と結びつける。「the range」「these findings」「such behavior」が何を指すかを必ず問う。指示対象は挿入位置より前に登場している必要がある。",
      "bodyEn": "When there are no discourse markers, look for pronoun references and vocabulary echoes that link the new sentence to a specific preceding sentence. Always ask what \"the range\" / \"these findings\" / \"such behavior\" refer to — the referent must appear before the insertion point.",
      "task": "Academic",
      "taskJp": "アカデミック"
    }
  ],
  "listening": [
    {
      "titleJp": "メモの取り方",
      "titleEn": "How to take notes",
      "bodyJp": "問題は何か？解決策は何か？をキーワードだけメモ。全文書き取ろうとしない！",
      "bodyEn": "Note only the keywords for 'What is the problem? What is the solution?' Do not try to transcribe everything!",
      "task": "Conversation",
      "taskJp": "会話"
    },
    {
      "titleJp": "問題解決パターン",
      "titleEn": "Problem-solving pattern",
      "bodyJp": "挨拶→問題提示→解決策提案→結論。キャンパス会話の多くはこのパターンに従う",
      "bodyEn": "Greeting → problem → proposed solution → conclusion. Most campus conversations follow this pattern.",
      "task": "Conversation",
      "taskJp": "会話"
    },
    {
      "titleJp": "感情表現に注目",
      "titleEn": "Watch for emotion words",
      "bodyJp": "That would be great! / That's a problem. → 話者の感情は頻出の設問ポイント",
      "bodyEn": "'That would be great!' / 'That's a problem.' → speakers' feelings are a frequent question target.",
      "task": "Conversation",
      "taskJp": "会話"
    },
    {
      "titleJp": "条件文に注目",
      "titleEn": "Watch conditional sentences",
      "bodyJp": "\"If...\"で始まる文は結果を問う設問のヒント。数字・手順の順序も設問になりやすい",
      "bodyEn": "Sentences starting with 'If...' often signal 'what is the result?' questions. Numbers and step orders are also common question targets.",
      "task": "Conversation",
      "taskJp": "会話"
    },
    {
      "titleJp": "2人の役割を区別",
      "titleEn": "Distinguish the two roles",
      "bodyJp": "学生＝問題を持ち込む側、スタッフ＝解決策を提示する側。役割を意識してメモ",
      "bodyEn": "Student = the one with the problem; staff = the one with the solution. Take notes with the roles in mind.",
      "task": "Conversation",
      "taskJp": "会話"
    },
    {
      "titleJp": "最後の発言に注意",
      "titleEn": "Watch the closing line",
      "bodyJp": "結論・次のアクションは会話の終盤に出ることが多い。「I'll...」に全集中！",
      "bodyEn": "Conclusions and next actions usually come near the end. Lock in on 'I'll...'!",
      "task": "Conversation",
      "taskJp": "会話"
    },
    {
      "titleJp": "4つの焦点で聞く",
      "titleEn": "Listen for the four W's",
      "bodyJp": "WHO（誰が）・WHAT（何を）・WHEN（いつ）・WHERE（どこで）を聞き逃さない",
      "bodyEn": "Don't miss WHO, WHAT, WHEN, WHERE.",
      "task": "Announcement",
      "taskJp": "アナウンス"
    },
    {
      "titleJp": "目的問題は冒頭に答え",
      "titleEn": "Purpose answers come at the start",
      "bodyJp": "「What is the announcement about?」の答えは最初の1〜2文にある。冒頭に全集中！",
      "bodyEn": "The answer to 'What is the announcement about?' is in the first one or two sentences. Focus on the opening!",
      "task": "Announcement",
      "taskJp": "アナウンス"
    },
    {
      "titleJp": "推奨・次のアクションは末尾",
      "titleEn": "Recommendations come at the end",
      "bodyJp": "「What does the speaker recommend?」の答えは最後の文に隠れていることが多い",
      "bodyEn": "The answer to 'What does the speaker recommend?' is often hidden in the last line.",
      "task": "Announcement",
      "taskJp": "アナウンス"
    }
  ],
  "writing": [
    {
      "titleJp": "主語と動詞を見つける",
      "titleEn": "Find the subject and verb",
      "bodyJp": "「誰が（主語）」「どうする（動詞）」を最初に探す。この2つが文の骨格。",
      "bodyEn": "Look first for who (the subject) and what they do (the verb). These two form the backbone of the sentence.",
      "task": "Build a Sentence",
      "taskJp": "Build a Sentence"
    },
    {
      "titleJp": "骨格を作る",
      "titleEn": "Build the skeleton",
      "bodyJp": "S+V を組み合わせて基本形を作る。文型（SV, SVC, SVO）を意識。",
      "bodyEn": "Combine S + V into a basic shape. Stay aware of the sentence pattern (SV, SVC, SVO).",
      "task": "Build a Sentence",
      "taskJp": "Build a Sentence"
    },
    {
      "titleJp": "残りを配置",
      "titleEn": "Place the rest",
      "bodyJp": "修飾語、前置詞句、接続詞を適切な位置に。最後に音読チェック（5秒）。",
      "bodyEn": "Slot modifiers, prepositional phrases, and conjunctions into the right spots. Finish with a 5-second read-aloud check.",
      "task": "Build a Sentence",
      "taskJp": "Build a Sentence"
    },
    {
      "titleJp": "問題文を読み3ポイントをメモ",
      "titleEn": "Read the prompt and jot down all 3 points",
      "bodyJp": "最初の30秒で3つのポイントを確認。見落とし＝大減点",
      "bodyEn": "Identify the 3 required points in the first 30 seconds. Missing one = big score loss.",
      "task": "Email",
      "taskJp": "メール"
    },
    {
      "titleJp": "構成を決める",
      "titleEn": "Plan the structure",
      "bodyJp": "Dear → 挨拶 → Point 1 → Point 2 → Point 3 → 締め。テンプレを頭に入れる",
      "bodyEn": "Dear → opening → Point 1 → Point 2 → Point 3 → closing. Keep the template ready.",
      "task": "Email",
      "taskJp": "メール"
    },
    {
      "titleJp": "書く（各ポイント2-3文）",
      "titleEn": "Write (2–3 sentences per point)",
      "bodyJp": "冗長にする必要なし。80〜120語で十分",
      "bodyEn": "No need to pad. 80–120 words is enough.",
      "task": "Email",
      "taskJp": "メール"
    },
    {
      "titleJp": "見直し・修正",
      "titleEn": "Review and revise",
      "bodyJp": "3ポイント全部入ってるか？スペルミスはないか？を最終確認",
      "bodyEn": "Check that all 3 points are in and there are no spelling errors.",
      "task": "Email",
      "taskJp": "メール"
    },
    {
      "titleJp": "主張",
      "titleEn": "Your claim",
      "bodyJp": "I believe that...質問に対して立場を明確に",
      "bodyEn": "I believe that...State your position on the question.",
      "task": "Discussion",
      "taskJp": "ディスカッション"
    },
    {
      "titleJp": "理由",
      "titleEn": "Reason",
      "bodyJp": "なぜその主張をするのか抽象的でなく具体的に",
      "bodyEn": "Why you hold that view.Be concrete, not abstract.",
      "task": "Discussion",
      "taskJp": "ディスカッション"
    },
    {
      "titleJp": "具体例",
      "titleEn": "Specific example",
      "bodyJp": "理由を裏付ける例を1つ1つだけ深く掘り下げる",
      "bodyEn": "One example that supports your reason.Develop just one in depth.",
      "task": "Discussion",
      "taskJp": "ディスカッション"
    },
    {
      "titleJp": "他の学生への言及",
      "titleEn": "Reference to other students",
      "bodyJp": "I agree with...Building on what X said...",
      "bodyEn": "I agree with...Building on what X said...",
      "task": "Discussion",
      "taskJp": "ディスカッション"
    }
  ],
  "speaking": [
    {
      "titleJp": "チャンクで記憶する",
      "titleEn": "Memorize in chunks",
      "bodyJp": "文全体を覚えようとせず、意味のかたまりで区切る。",
      "bodyEn": "Don't try to memorize the whole sentence — break it into meaningful chunks.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "リズムとイントネーションをコピー",
      "titleEn": "Copy the rhythm and intonation",
      "bodyJp": "強弱とメロディーを真似る。単語を正確に言うだけでなく、英語らしいリズムで話すことが重要。",
      "bodyEn": "Mirror the stress pattern and melody. Pronouncing each word correctly isn't enough — speaking with a natural English rhythm matters just as much.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "録音開始後、2～3秒待つ",
      "titleEn": "Wait 2–3 seconds after recording starts",
      "bodyJp": "焦らず、最初の単語を噛みにくくなる。落ち着いて始めることで、全体の流れが良くなる。",
      "bodyEn": "Don't rush — you're less likely to stumble on the first word. Starting calmly improves the whole delivery.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "間違えても止まらない",
      "titleEn": "Don't stop when you make a mistake",
      "bodyJp": "言い直して続ける方が高得点。止まると流暢性の評価が下がる。",
      "bodyEn": "Restating and continuing scores higher. Stopping hurts your fluency score.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "自主練習の方法",
      "titleEn": "How to practice on your own",
      "bodyJp": "Step 1: 各文を、チャンクごとに区切って音読する（ゆっくり） Step 2: チャンクを繋げて、文全体を通して音読する（自然なスピード） Step 3: スマホのタイマーを制限時間にセットし、音読する → 時間内に言い切れるか確認 Step 4: スマホの録音機能で自分の声を録音し、聞き返す → イントネーションやリズムをチェック 目標： 短い文がスムーズに言えるようになれば、本番でも十分対応できる。長い文は完璧でなくてもOK — 途中で止まらず最後まで言い切ることが最優先！",
      "bodyEn": "Step 1: Read each sentence aloud, pausing at every chunk boundary (slowly). Step 2: Connect the chunks and read the whole sentence at natural speed. Step 3: Set your phone timer to the test limit and read aloud — check whether you can finish in time. Step 4: Record yourself with your phone, then listen back and check intonation and rhythm. Goal: Once short sentences flow smoothly, you'll handle the real test fine. Long sentences don't need to be perfect — what matters most is finishing without stopping.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "チャンクで記憶する",
      "titleEn": "Memorize in chunks",
      "bodyJp": "文全体を覚えようとせず、意味のかたまりで区切る。",
      "bodyEn": "Don't try to memorize the whole sentence — break it into meaningful chunks.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "リズムコピー：空港アナウンストーンを再現",
      "titleEn": "Mirror the rhythm: reproduce the airport announcement tone",
      "bodyJp": "空港の案内放送は、落ち着いた丁寧なトーンと、重要語を強調するイントネーションが特徴。",
      "bodyEn": "Airport announcements have a calm, courteous tone and intonation that emphasizes key words.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "空港特有のリンキングポイント",
      "titleEn": "Airport-specific linking points",
      "bodyJp": "空港フレーズでは、前置詞や関係詞のつながりが自然さを左右する。",
      "bodyEn": "In airport phrases, linking through prepositions and connectors decides whether you sound natural.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "長文は「役割」で分けて覚える",
      "titleEn": "Memorize long sentences by role",
      "bodyJp": "24語の文も、役割ごとに分ければ覚えやすい。",
      "bodyEn": "Even a 24-word sentence becomes manageable when broken down by functional role.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "チャンク記憶で長文を攻略",
      "titleEn": "Conquer long sentences with chunk memorization",
      "bodyJp": "長い文を一語ずつ覚えようとすると短期記憶がパンクする。意味のかたまり（チャンク）で覚えることで、脳の負荷を大幅に減らせる。",
      "bodyEn": "Trying to remember a long sentence word-by-word overloads short-term memory. Memorizing in meaningful chunks dramatically reduces the cognitive load.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "リズムコピーで自然さをアップ",
      "titleEn": "Mirror the rhythm for natural delivery",
      "bodyJp": "単語を正確に言うだけでは不十分。ネイティブの強弱リズムをそのままコピーすることが高得点のカギ。",
      "bodyEn": "Pronouncing each word correctly isn't enough. Copying the native speaker's stress pattern is the key to a high score.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "聞き終わってから2秒待つ",
      "titleEn": "Wait 2 seconds after the audio ends",
      "bodyJp": "音声が終わった瞬間に焦って話し始めると、最初の単語を噛みやすい。2秒間で文全体を頭の中で整理してから話し始める。",
      "bodyEn": "Rushing to speak the moment the audio ends often causes you to stumble on the first word. Take 2 seconds to organize the whole sentence in your head before starting.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "録音開始後、2～3秒待つ",
      "titleEn": "Wait 2–3 seconds after recording starts",
      "bodyJp": "焦らず、最初の単語を噛みにくくなる。落ち着いて始めることで、全体の流れが良くなる。",
      "bodyEn": "Don't rush — you're less likely to stumble on the first word. Starting calmly improves the whole delivery.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "チャンクで記憶する",
      "titleEn": "Memorize in chunks",
      "bodyJp": "文全体を覚えようとせず、意味のかたまりで区切る。",
      "bodyEn": "Don't try to memorize the whole sentence — break it into meaningful chunks.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "リズムコピー：接客トーンを再現",
      "titleEn": "Mirror the rhythm: reproduce the service tone",
      "bodyJp": "レストラン接客では、丁寧さと温かさを伝えるイントネーションが重要。",
      "bodyEn": "In restaurant service, intonation that conveys politeness and warmth matters most.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "レストラン特有のリンキングポイント",
      "titleEn": "Restaurant-specific linking points",
      "bodyJp": "接客フレーズでは、単語のつながり（リンキング）が自然さを左右する。",
      "bodyEn": "In service phrases, linking between words decides whether you sound natural.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "リズムとイントネーションをコピー",
      "titleEn": "Copy the rhythm and intonation",
      "bodyJp": "強弱とメロディーを真似る。単語を正確に言うだけでなく、英語らしいリズムで話すことが重要。",
      "bodyEn": "Mirror the stress pattern and melody. Pronouncing each word correctly isn't enough — speaking with a natural English rhythm matters just as much.",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "45秒の使い方",
      "titleEn": "How to use the 45 seconds",
      "bodyJp": "時間配分を決めておくと、沈黙を避けて内容を詰め込める。",
      "bodyEn": "Decide your time allocation in advance to avoid silence and pack in content.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "沈黙を避けるフレーズ",
      "titleEn": "Phrases to avoid silence",
      "bodyJp": "困ったときに使えるフレーズを事前に準備しておく。",
      "bodyEn": "Prepare go-to phrases for moments when you're stuck.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "失敗パターンとリカバリー",
      "titleEn": "Failure patterns and recovery",
      "bodyJp": "✗ NG： 5秒以上の沈黙 ✓ OK： → \"Well, let me think...\" でつなぐ",
      "bodyEn": "✗ NG: 5+ seconds of silence ✓ OK: bridge with \"Well, let me think...\"",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "使い回せる具体例ストック",
      "titleEn": "Stock of reusable examples",
      "bodyJp": "どんなトピックでも使えるエピソードを5つ準備しておく。",
      "bodyEn": "Prepare 5 anecdotes that work for any topic.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "自主練習の方法",
      "titleEn": "How to practice on your own",
      "bodyJp": "Step 1: スマホのタイマーを45秒にセットする Step 2: 質問を声に出して読む（本番では音声で流れる部分） Step 3: 読み終わったらすぐタイマースタート → 45秒以内に「主張→理由→具体例→まとめ」を言い切る Step 4: 録音して聞き返す → 沈黙がないか、まとめまで到達しているかチェック 💡 本番では質問は音声のみ（画面にテキストは表示されません）。聞いた瞬間に回答を組み立てる練習が重要！ 目標： 1日2〜3回のルーティンを体に覚えさせる。完璧な英語でなくてOK — 止まらず話し続けることが最優先！",
      "bodyEn": "Step 1: Set your phone timer to 45 seconds. Step 2: Read the question aloud (in the real test it plays as audio). Step 3: Start the timer the moment you finish reading → deliver claim → reason → example → wrap-up within 45 seconds. Step 4: Record yourself and listen back → check for silences and confirm you reached the wrap-up. 💡 In the real test the question is audio only (no text on screen). Practice composing your answer the moment you hear the question! Goal: Build a 2–3-times-a-day routine until it becomes automatic. Perfect English isn't required — not stopping is what matters most.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "45秒の使い方",
      "titleEn": "How to use the 45 seconds",
      "bodyJp": "時間配分を決めておくと、沈黙を避けて内容を詰め込める。",
      "bodyEn": "Decide your time allocation in advance to avoid silence and pack in content.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "理由は「1つ深く」が鉄則",
      "titleEn": "Rule: one reason, deep",
      "bodyJp": "理由を2つ挙げようとすると、どちらも中途半端になりがち。1つの理由を深く掘り下げて、具体例まで到達するのが高得点パターン。",
      "bodyEn": "Trying to give two reasons usually leaves both half-developed. The high-scoring pattern is to dig deeply into one reason and reach a concrete example.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "旅行トピックで使える具体例ストック",
      "titleEn": "Reusable travel-topic examples",
      "bodyJp": "どんな質問にも応用できるエピソードを準備しておく。",
      "bodyEn": "Prepare anecdotes that work across any travel question.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "45秒の時間配分",
      "titleEn": "45-second time allocation",
      "bodyJp": "45秒は短いようで、テンプレートに沿えば十分な内容を詰め込める。時間配分を体に覚えさせることが重要。",
      "bodyEn": "45 seconds may seem short, but with a template you can fit plenty of content. Internalizing the timing is the key.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "Health テーマで使えるフレーズ",
      "titleEn": "Phrases for the Health theme",
      "bodyJp": "健康・フィットネスの話題で頻出するフレーズを事前に準備しておく。",
      "bodyEn": "Prepare phrases that come up often in health and fitness topics.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "よくある失敗パターンと対策",
      "titleEn": "Common failure patterns and fixes",
      "bodyJp": "✗ NG： 具体例なしで抽象的に話し続ける ✓ OK： → \"For example, last month I started jogging...\" のように自分の体験を入れる",
      "bodyEn": "✗ NG: talking abstractly with no concrete example ✓ OK: drop in your own experience, e.g. \"For example, last month I started jogging...\"",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "食べ物トピックで使えるフィラーフレーズ",
      "titleEn": "Filler phrases for food topics",
      "bodyJp": "困ったときに時間を稼ぐフレーズを準備しておく。",
      "bodyEn": "Prepare phrases for buying time when you're stuck.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "食べ物トピックで使える具体例ストック",
      "titleEn": "Reusable food-topic examples",
      "bodyJp": "どんな質問にも応用できるエピソードを準備しておく。",
      "bodyEn": "Prepare anecdotes that work across any food question.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "45秒の構成：主張→理由→具体例→まとめ",
      "titleEn": "45-second structure: claim → reason → example → wrap-up",
      "bodyJp": "45秒を以下のように配分する。全パートを言い切ることが最重要。",
      "bodyEn": "Split your 45 seconds like this. The key is finishing all four parts.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "万能テンプレート",
      "titleEn": "All-purpose template",
      "bodyJp": "この4ステップを覚えれば、どんな質問にも対応できる。",
      "bodyEn": "Memorize these 4 steps and you'll be ready for any question.",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    }
  ]
};
