/* Auto-generated by tools/extract-tips.py — do not edit by hand. */
window.TCK_TIPS = {
  "reading": [
    {
      "titleJp": "品詞を特定してから埋める",
      "titleEn": "Identify the part of speech first",
      "bodyJp": "冠詞＋空欄 → 名詞／主語＋空欄 → 動詞／be 動詞＋空欄 → 形容詞・過去分詞／空欄＋名詞 → 形容詞",
      "bodyEn": "Article + blank → noun · Subject + blank → verb · Be + blank → adj/participle · Blank + noun → adj",
      "task": "CTW",
      "taskJp": "CTW"
    },
    {
      "titleJp": "頻出パターンを暗記する",
      "titleEn": "Memorize recurring patterns",
      "bodyJp": "however, therefore, although, particularly, significant, demonstrate, evidence … 見たら即座に埋められるように。",
      "bodyEn": "however, therefore, although, particularly, significant, demonstrate, evidence — recognize them instantly.",
      "task": "CTW",
      "taskJp": "CTW"
    },
    {
      "titleJp": "推測でも必ず埋めるAlways fill the blank",
      "titleEn": "Always fill the blank",
      "bodyJp": "正解 → 得点／不正解 → 0 点／空欄 → 0 点。推測しないと損。",
      "bodyEn": "Correct → points · Wrong → 0 · Blank → 0. Guessing costs nothing.",
      "task": "CTW",
      "taskJp": "CTW"
    },
    {
      "titleJp": "Intro と Conclusion を先に読む",
      "titleEn": "Read intro and conclusion first",
      "bodyJp": "最初と最後の文でトピックと流れを掴む。推測精度が上がる。",
      "bodyEn": "The opening and closing sentences tell you the topic and flow — better context, better guesses.",
      "task": "CTW",
      "taskJp": "CTW"
    },
    {
      "titleJp": "推測でも必ず埋める",
      "titleEn": "Always fill the blank",
      "bodyJp": "正解 → 得点 / 不正解 → 0点 / 空欄 → 0点",
      "bodyEn": "Correct → points / Wrong → 0 / Blank → 0",
      "task": "CTW",
      "taskJp": "CTW"
    },
    {
      "titleJp": "INTROとCONCLUSIONを先に読む",
      "titleEn": "",
      "bodyJp": "最初と最後の文を先に読めば、トピックと流れが掴める。空欄の推測精度が上がる！",
      "bodyEn": "",
      "task": "CTW",
      "taskJp": "CTW"
    },
    {
      "titleJp": "冒頭のキーワードから目的を特定する",
      "titleEn": "Identify the purpose from opening keywords",
      "bodyJp": "最初の1〜2文に文章の目的が示されている。次のパターンを覚えておこう。通知: We are pleased to inform... / We would like to inform you...依頼: Could you... / I would appreciate if...確認: I'm writing to confirm...謝罪: I apologize for... / Unfortunately...",
      "bodyEn": "The first 1-2 sentences reveal the purpose of the text. Learn the patterns:Notification: We are pleased to inform... / We would like to inform you...Request: Could you... / I would appreciate if...Confirmation: I'm writing to confirm...Apology: I apologize for... / Unfortunately...",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "NOT/EXCEPT問題は消去法で",
      "titleEn": "NOT/EXCEPT: Use elimination",
      "bodyJp": "手順:1. 設問内の NOT/EXCEPT に印をつける2. 各選択肢をパッセージと一つずつ照らし合わせる3. パッセージに書かれている3つの選択肢を消す。残った1つが正解。",
      "bodyEn": "Steps:1. Circle NOT/EXCEPT in the question2. Check each option against the passage one by one3. Cross out the 3 options that ARE mentioned in the passage. The remaining one is the answer.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "推論問題は本文から離れない",
      "titleEn": "Inference questions: stick to the text",
      "bodyJp": "推論問題では、答えはパッセージの情報から論理的に導かれるものでなければならない。自分の知識や思い込みを混ぜないこと。",
      "bodyEn": "For inference questions, the answer must be logically supported by information in the passage. Do not mix in your own knowledge or assumptions.",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "For NOT/EXCEPT, verify each option",
      "titleEn": "",
      "bodyJp": "In \"all of the following EXCEPT\" questions, three options are in the passage and one is not. Check each option against the text — the odd one out is your answer. Q2: The notice mentions the outdoor track (A), online fitness classes (B), and Hartley Hall fitness room (D). A public community pool (C) is never discussed, so C is the answer.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Inference from consequences",
      "titleEn": "",
      "bodyJp": "Notices often include deadlines. If a deadline is stated, think about what happens after it passes — that is usually what an inference question targets. Trap: Do not invent extra consequences (fees, penalties) that the notice never mentions.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "SMS: follow the conversation flow",
      "titleEn": "",
      "bodyJp": "Text messages move fast. Read each bubble in order and note who agrees, who disagrees, and what plan is made at the end. The final bubbles usually settle the plan. Q5: The last messages settle on a Zoom video call at 4:00 PM to review the essay draft, not an in-person meeting.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Identify the purpose from opening keywords (目的特定)",
      "titleEn": "",
      "bodyJp": "The first 1-2 sentences reveal the purpose of the text. Learn the patterns: Notification: We are pleased to inform... / We would like to inform you... Reminder: This is a reminder that... / Please be advised... Promotion: Sign up before... / Limited time offer... Invitation: You are invited to... / We are hosting... Q4: The ad opens with a question to the reader and then introduces a \"spring deal\" with a discounted rate for students. The whole text is built around promoting this offer = A.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "NOT/EXCEPT: Use elimination (NOT問題消去法)",
      "titleEn": "",
      "bodyJp": "手順:",
      "bodyEn": "Steps:",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Inference questions: stick to the text (推論は本文のみ)",
      "titleEn": "",
      "bodyJp": "For inference questions, the answer must be logically supported by information in the passage. Do not mix in your own knowledge or assumptions. Q6: The ad says \"All instruments except drums are available to borrow during your lesson.\" From the word \"except,\" we can infer that drum students must bring or buy their own instrument = C.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Social media posts: read the caption, not just the image",
      "titleEn": "",
      "bodyJp": "Social media posts pack a lot of information into a short text. The main purpose is usually in the first 1-2 sentences, while specific instructions (what to bring, who to contact) appear later. Hashtags and emoji are decorative — focus on the body paragraphs. Q1: \"Our free Biology 201 study circle is back this week!\" plus the meeting time signals an invitation to a recurring meeting = B.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Schedules: match the event to the time column",
      "titleEn": "",
      "bodyJp": "For schedule passages, your finger should move horizontally: find the row, check the time, then read the event. For EXCEPT questions, use the intro or footnotes to catch items that cost extra or require separate tickets. Trap: \"Included with ID\" options often hide one paid event (e.g., meal tickets sold separately). Always re-read intro and notes.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Inference: find the single supporting sentence",
      "titleEn": "",
      "bodyJp": "The correct inference answer is logically supported by one specific sentence. If you can't point to a sentence that supports it, it's probably a distractor. Q6: The schedule note says \"the Main Stage events will be moved to the Student Union Ballroom\" in case of heavy rain. That directly supports \"moved to an indoor space\" = C.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Text messages: track who says what",
      "titleEn": "",
      "bodyJp": "In SMS threads, causes, conditions, and promises are spread across speakers. Before answering, identify which bubble contains the specific fact — do not confuse your own message with the other person's. Q1: Maya writes \"Final inspection is Saturday at 10am.\" The cleaning date is set by the inspection, not by the shampooer or work schedules = B.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "EXCEPT questions: eliminate what IS stated",
      "titleEn": "",
      "bodyJp": "For EXCEPT or NOT questions, find each option in the passage and cross it off if it appears. The one you cannot find is the answer. Q4: 3D printers (paragraph 3), soundproof rooms (paragraph 3), and the student cafe (paragraph 3) are all listed. Sleeping pods are never mentioned = D.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Quoted speech signals inference clues",
      "titleEn": "",
      "bodyJp": "When a news article quotes someone directly, the quote usually carries the implied argument. Paraphrase the speaker's point in your own words before scanning options. Common trap: Options that exaggerate (\"will replace all,\" \"charge less\") go beyond what the quote supports. Choose the answer that restates the speaker's idea without adding new claims.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Read forms like a table of facts",
      "titleEn": "",
      "bodyJp": "Forms store one fact per row. Match the question's key phrase to the left-hand label and read only that row's value. Most form questions are directly factual. Q1: The question asks about \"permit zone requested.\" Find that row: \"Zone C — West Commuter Lot\" = C.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Use small notes for what they imply",
      "titleEn": "",
      "bodyJp": "Forms often include a small Note or footnote. These are the source of inference questions — the note tells you what is and is not permitted. Q2: The note says Zone C is valid only Mon–Fri, 7 AM–8 PM. Therefore, leaving the car on Sunday is not permitted = A.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Receipts: read the totals block carefully",
      "titleEn": "",
      "bodyJp": "A receipt question is usually about how a discount, tax, or fee was applied. Look at the label next to the amount, not just the number. Q3: The line reads \"Student discount (10%, books only).\" That tells you both the rate and the scope = B. Common trap: Q5 asks what can be inferred about sales tax. Tax is \"6.5%, non-book items\" — books were not taxed, which means textbooks are exempt = B.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Track who says what in a group chat",
      "titleEn": "",
      "bodyJp": "In a group conversation, each message is tied to a specific sender. Questions often ask what a particular person will do. Read the sender's name first, then locate their statement — don't mix up tasks between members. Q2: Daniel says \"I'll draft the survey and send it out to classmates tomorrow.\" That is his task, not Raj's (literature review) or Sofia's (video) = A.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Inference: stay close to what is actually said",
      "titleEn": "",
      "bodyJp": "よくある罠:",
      "bodyEn": "Common traps:",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Advertisements: watch conditions on discounts",
      "titleEn": "",
      "bodyJp": "Ad passages usually include multiple offers with different conditions (early bird, student discount, membership, etc.). Questions often test whether you can match the offer to its exact condition. Underline the deadline or requirement for each discount on your first read. Q4: The Early Bird Special requires registering \"before April 25.\" The 10% discount for having a student ID is a different offer. = C.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "NOT/EXCEPT: eliminate what is mentioned",
      "titleEn": "",
      "bodyJp": "手順:",
      "bodyEn": "Steps:",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Schedules: read the headers and the footnotes",
      "titleEn": "",
      "bodyJp": "A schedule has two layers of information: the table itself (days, hours, names) and the notes above or below (rules and exceptions). Questions often target the notes. Q2: The schedule's intro says sessions are \"limited to 25 minutes per student when others are waiting.\" A busy day therefore means a shorter session = B.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Menus: scan the descriptions for optional phrases",
      "titleEn": "",
      "bodyJp": "Common option signals on a menu: Add X for $Y / available on request / choose from ... If an EXCEPT question asks which option is not offered, an answer that sounds reasonable but is never written on the menu is the trap you are looking for. Trap: common real-world substitutions (e.g. almond milk for buttermilk) that the menu simply does not mention.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Inference = what must be true, not what might be true",
      "titleEn": "",
      "bodyJp": "A correct inference is directly supported by the text. If you have to add outside knowledge or make a new assumption, it is probably a distractor. Q5: The menu says \"students save 15% with a valid campus ID.\" A 15% discount must mean the student pays less than the printed price = B.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "News articles: separate facts from background",
      "titleEn": "",
      "bodyJp": "News articles open with the core event (\"who did what, when, where\"). Later paragraphs add reasons, quotes, and future plans. For factual questions, locate the specific paragraph that deals with that sub-topic rather than re-reading the whole article. Q2: The funding question is answered only in paragraph 3: \"Funding for the saplings came from a grant... tools and refreshments were donated by local businesses.\" = C.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Inference: check the future-tense sentences",
      "titleEn": "",
      "bodyJp": "When an article ends with a sentence about \"plans to,\" \"will hold,\" or \"goal of,\" that line is often the basis for inference questions. The writer is telling you what comes next — use that to draw conclusions about the organization or the event. Q3: \"Green Roots plans to hold a second planting session in October, with a goal of reaching 1,500 trees.\" This directly supports \"The group intends to continue its planting work\" = B.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Social media posts: read the informal tone carefully",
      "titleEn": "",
      "bodyJp": "Social posts are short and casual, but every phrase carries information. \"Honestly, my Portuguese is still rough, but the staff keep switching to English to help me out\" shows both a difficulty and a positive response. For inference, ask: \"What attitude or situation does the writer's word choice reveal?\" Q5: The coworkers \"switching to English to help me out\" signals they are being flexible and supportive about the language gap = A.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Student-to-professor emails: find the single \"ask\"",
      "titleEn": "",
      "bodyJp": "Polite request emails often open with pleasantries and background before getting to the point. Look for phrases like: The ask: I was hoping you might... / Would you be willing to... / I would appreciate it if you could... Background (skip for purpose Qs): Since I completed... / As you may recall... Q1: The sentence \"I was hoping you might be willing to write one on my behalf\" (referring to a letter of recommendation) is the true purpose = A. The rest is context.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Reading forms: scan by section headers",
      "titleEn": "",
      "bodyJp": "Forms are organized into labeled sections (Applicant Info, Preferences, etc.). Don't read top-to-bottom — jump to the section named in the question. Q3: The question asks about \"first-choice placement\" → go directly to the Placement Preference section → read the \"1st Choice\" field = B (Harwick Marine Institute — Field Research Assistant).",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "NOT / EXCEPT questions: check every option against the text",
      "titleEn": "",
      "bodyJp": "For negative factual questions, three of the four options ARE mentioned in the passage. Your job is to find the one that is NOT there. Strategy: Check off each option as you locate it in the form. The remaining unchecked option is your answer. Q4: Year ✓ (Junior), Major ✓ (Environmental Science), Submission date ✓ (03/06/2026). GPA is never listed anywhere = C.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Inference from checkboxes: combine the label with the check",
      "titleEn": "",
      "bodyJp": "A checkbox carries two pieces of info: the statement and whether it's selected. The inference usually comes from pairing them with nearby qualifying text (e.g., \"housing stipend required\"). Q5: \"Willing to relocate ✓ (housing stipend required)\" + \"Available for unpaid placements ✗\" → he can move, but he needs housing support = C.",
      "bodyEn": "",
      "task": "RDL",
      "taskJp": "RDL"
    },
    {
      "titleJp": "Correct answers are always paraphrases",
      "titleEn": "",
      "bodyJp": "この練習からの言い換え例:",
      "bodyEn": "Paraphrase examples from this practice:",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Understand passage structure",
      "titleEn": "",
      "bodyJp": "First sentence → Topic / Main claim Middle → Details, examples, data Last sentence → Conclusion / Summary Main Idea questions can often be solved by reading just the first and last sentences. Q1: Passage 1 opens with \"The invention of writing is widely regarded as one of the most significant achievements\" and ends with \"they all followed a comparable path: from pictures, to symbols for words, to symbols for sounds.\" Together these give the main idea: how writing systems originated and evolved = A.",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Inference must come from the text only",
      "titleEn": "",
      "bodyJp": "最もよくある間違い:",
      "bodyEn": "Most common mistake:",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Main Idea: first + last sentences are key",
      "titleEn": "",
      "bodyJp": "罠のパターン:",
      "bodyEn": "Trap pattern:",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Key Takeaways",
      "titleEn": "",
      "bodyJp": "1. Correct answers are always paraphrases of the passage. Options using the same words as the passage are often traps. 2. For inference questions, only the passage counts as evidence. Do not mix in your own knowledge or opinions. 3. Main Idea = first sentence + last sentence. Do not get pulled into middle-paragraph details. 4. Vocabulary in Context: substitute and check. Replace the word with each option and see which one reads most naturally.",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Vocabulary in Context: substitute and check",
      "titleEn": "",
      "bodyJp": "Replace the target word with each option and see which one reads most naturally in the sentence. Q2: \"One of the most [very deep and significant] effects of industrialization was the rapid growth of cities\" reads naturally and matches the context of massive societal change. \"Temporary\" contradicts the lasting impact described; \"slightly noticeable\" is the opposite.",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Rhetorical Purpose: ask \"what point is the author making?\"",
      "titleEn": "",
      "bodyJp": "罠のパターン:",
      "bodyEn": "Trap pattern:",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Correct answers are always paraphrases (パラフレーズを見抜く)",
      "titleEn": "",
      "bodyJp": "この練習からの言い換え例:",
      "bodyEn": "Paraphrase examples from this practice:",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Vocabulary: identify the part of speech first (品詞特定)",
      "titleEn": "",
      "bodyJp": "Before looking at options, determine if the target word is a noun, verb, adjective, or adverb. Then substitute each option into the sentence to check which one fits both grammatically and logically. Q2: \"it cools and condenses into tiny droplets\" — \"condenses\" is a verb. Substitute: \"changes from gas to liquid into tiny droplets\" reads naturally. \"Disappears completely\" and \"expands rapidly\" contradict the context of forming droplets.",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Rhetorical Purpose: read the sentence before and after (前後の文を読む)",
      "titleEn": "",
      "bodyJp": "When asked \"Why does the author mention X?\", the answer is usually found in the sentence immediately before the mention. The author states a claim, then provides X as an example or evidence. Q4: The sentence before says \"the range of social structures found in primates is remarkably diverse.\" The mention of marmosets (small groups) and baboons (large hierarchies) illustrates this diversity = A.",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Use elimination for difficult questions (消去法)",
      "titleEn": "",
      "bodyJp": "When unsure, eliminate options that contain extreme words (always, never, only, all, none) or information not found in the passage. Red-flag words to watch for: ✗ \"always,\" \"never,\" \"only,\" \"all,\" \"none,\" \"completely,\" \"the most\" ✓ Correct answers tend to use moderate language: \"some,\" \"often,\" \"may,\" \"tend to\"",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Rhetorical Purpose: ask \"why,\" not \"what\"",
      "titleEn": "",
      "bodyJp": "Purpose questions ask why the author mentions something, not what it means. Look at the sentence before the mentioned detail — it usually contains the claim the example is meant to support. Q4: Before mentioning cacti and rainforest plants, paragraph 3 states that \"different species have developed remarkable adaptations.\" The examples illustrate this claim = D.",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Sentence Insertion: use discourse markers as clues",
      "titleEn": "",
      "bodyJp": "Words like \"Furthermore,\" \"However,\" \"For example,\" \"In contrast,\" at the beginning of the inserted sentence tell you how it connects to the surrounding text. Match the discourse marker to the logical relationship between the sentences. Q6: \"Furthermore\" signals additional information. The sentence about improved crops in tropical regions adds to the idea of developing resilient crop varieties in the previous sentence = B.",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Rhetorical Purpose: ask \"why did the author include this?\"",
      "titleEn": "",
      "bodyJp": "Purpose questions ask about the function of a detail, not its content. Ask yourself: \"What point is the author trying to make by mentioning this?\" The answer usually connects the detail back to the paragraph's main claim. Q4: Galileo's discovery of Jupiter's moons is mentioned right after the topic sentence about telescopes transforming astronomy. The discovery serves as evidence that telescopes revealed facts challenging the geocentric model = A.",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Inference: each advance = new capability",
      "titleEn": "",
      "bodyJp": "When a passage describes a series of developments, look for the pattern. If each new technology is described as revealing something new, you can infer that progress means expanded capability. Q6: The passage describes optical telescopes revealing moons, reflecting telescopes observing fainter objects, radio telescopes detecting invisible radiation, and space telescopes imaging distant galaxies. The pattern: each advance revealed previously undetectable phenomena = C.",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Rhetorical purpose: ask \"why did the author include this?\"",
      "titleEn": "",
      "bodyJp": "Purpose questions ask about the function of a detail, not the detail itself. Look at the sentence before the mentioned detail — it usually states the point the example supports. Q4: Before mentioning neutrophils and macrophages, the passage says \"general-purpose immune cells that respond quickly to any foreign substance.\" The examples illustrate cells involved in the body's immediate defense = A.",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Rhetorical Purpose: ask \"Why did the author include this?\"",
      "titleEn": "",
      "bodyJp": "When you see a specific example in the passage, ask yourself: What general point was the author trying to support? The answer to a purpose question is never about the example itself — it is about the larger claim. Q4: The Himalayas are mentioned right after the sentence about plate collision causing mountain formation. The example illustrates this process = D.",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    },
    {
      "titleJp": "Sentence Insertion: follow the referents",
      "titleEn": "",
      "bodyJp": "When there are no discourse markers (like \"Furthermore\" or \"In contrast\"), look for pronoun references and vocabulary echoes that connect the new sentence to a specific preceding sentence. Q6 example: \"the range\" and \"the two plates\" in the insertion sentence can only refer to the Himalayas and the Indian/Eurasian Plates mentioned in sentence 3. This tells you the sentence must go at position C. Common mistake: Choosing a position where the sentence \"sounds okay\" without checking whether the pronoun references and vocabulary actually match. Always ask: What does \"the range\" / \"these findings\" / \"such behavior\" refer to? The referent must appear before the insertion point.",
      "bodyEn": "",
      "task": "Academic",
      "taskJp": "アカデミック"
    }
  ],
  "listening": [
    {
      "titleJp": "メモの取り方",
      "titleEn": "How to take notes",
      "bodyJp": "問題は何か？解決策は何か？をキーワードだけメモ。全文書き取ろうとしない！",
      "bodyEn": "Note only the keywords for 'What is the problem? What is the solution?' Do not try to transcribe everything!",
      "task": "Conversation",
      "taskJp": "会話"
    },
    {
      "titleJp": "問題解決パターン",
      "titleEn": "Problem-solving pattern",
      "bodyJp": "挨拶→問題提示→解決策提案→結論。キャンパス会話の多くはこのパターンに従う",
      "bodyEn": "Greeting → problem → proposed solution → conclusion. Most campus conversations follow this pattern.",
      "task": "Conversation",
      "taskJp": "会話"
    },
    {
      "titleJp": "感情表現に注目",
      "titleEn": "Watch for emotion words",
      "bodyJp": "That would be great! / That's a problem. → 話者の感情は頻出の設問ポイント",
      "bodyEn": "'That would be great!' / 'That's a problem.' → speakers' feelings are a frequent question target.",
      "task": "Conversation",
      "taskJp": "会話"
    },
    {
      "titleJp": "条件文に注目",
      "titleEn": "Watch conditional sentences",
      "bodyJp": "\"If...\"で始まる文は結果を問う設問のヒント。数字・手順の順序も設問になりやすい",
      "bodyEn": "Sentences starting with 'If...' often signal 'what is the result?' questions. Numbers and step orders are also common question targets.",
      "task": "Conversation",
      "taskJp": "会話"
    },
    {
      "titleJp": "2人の役割を区別",
      "titleEn": "Distinguish the two roles",
      "bodyJp": "学生＝問題を持ち込む側、スタッフ＝解決策を提示する側。役割を意識してメモ",
      "bodyEn": "Student = the one with the problem; staff = the one with the solution. Take notes with the roles in mind.",
      "task": "Conversation",
      "taskJp": "会話"
    },
    {
      "titleJp": "最後の発言に注意",
      "titleEn": "Watch the closing line",
      "bodyJp": "結論・次のアクションは会話の終盤に出ることが多い。「I'll...」に全集中！",
      "bodyEn": "Conclusions and next actions usually come near the end. Lock in on 'I'll...'!",
      "task": "Conversation",
      "taskJp": "会話"
    },
    {
      "titleJp": "4つの焦点で聞く",
      "titleEn": "Listen for the four W's",
      "bodyJp": "WHO（誰が）・WHAT（何を）・WHEN（いつ）・WHERE（どこで）を聞き逃さない",
      "bodyEn": "Don't miss WHO, WHAT, WHEN, WHERE.",
      "task": "Announcement",
      "taskJp": "アナウンス"
    },
    {
      "titleJp": "目的問題は冒頭に答え",
      "titleEn": "Purpose answers come at the start",
      "bodyJp": "「What is the announcement about?」の答えは最初の1〜2文にある。冒頭に全集中！",
      "bodyEn": "The answer to 'What is the announcement about?' is in the first one or two sentences. Focus on the opening!",
      "task": "Announcement",
      "taskJp": "アナウンス"
    },
    {
      "titleJp": "推奨・次のアクションは末尾",
      "titleEn": "Recommendations come at the end",
      "bodyJp": "「What does the speaker recommend?」の答えは最後の文に隠れていることが多い",
      "bodyEn": "The answer to 'What does the speaker recommend?' is often hidden in the last line.",
      "task": "Announcement",
      "taskJp": "アナウンス"
    }
  ],
  "writing": [
    {
      "titleJp": "主語と動詞を見つける",
      "titleEn": "Find the subject and verb",
      "bodyJp": "「誰が（主語）」「どうする（動詞）」を最初に探す。この2つが文の骨格。",
      "bodyEn": "Look first for who (the subject) and what they do (the verb). These two form the backbone of the sentence.",
      "task": "Build a Sentence",
      "taskJp": "Build a Sentence"
    },
    {
      "titleJp": "骨格を作る",
      "titleEn": "Build the skeleton",
      "bodyJp": "S+V を組み合わせて基本形を作る。文型（SV, SVC, SVO）を意識。",
      "bodyEn": "Combine S + V into a basic shape. Stay aware of the sentence pattern (SV, SVC, SVO).",
      "task": "Build a Sentence",
      "taskJp": "Build a Sentence"
    },
    {
      "titleJp": "残りを配置",
      "titleEn": "Place the rest",
      "bodyJp": "修飾語、前置詞句、接続詞を適切な位置に。最後に音読チェック（5秒）。",
      "bodyEn": "Slot modifiers, prepositional phrases, and conjunctions into the right spots. Finish with a 5-second read-aloud check.",
      "task": "Build a Sentence",
      "taskJp": "Build a Sentence"
    },
    {
      "titleJp": "問題文を読み3ポイントをメモ",
      "titleEn": "Read the prompt and jot down all 3 points",
      "bodyJp": "最初の30秒で3つのポイントを確認。見落とし＝大減点",
      "bodyEn": "Identify the 3 required points in the first 30 seconds. Missing one = big score loss.",
      "task": "Email",
      "taskJp": "メール"
    },
    {
      "titleJp": "構成を決める",
      "titleEn": "Plan the structure",
      "bodyJp": "Dear → 挨拶 → Point 1 → Point 2 → Point 3 → 締め。テンプレを頭に入れる",
      "bodyEn": "Dear → opening → Point 1 → Point 2 → Point 3 → closing. Keep the template ready.",
      "task": "Email",
      "taskJp": "メール"
    },
    {
      "titleJp": "書く（各ポイント2-3文）",
      "titleEn": "Write (2–3 sentences per point)",
      "bodyJp": "冗長にする必要なし。80〜120語で十分",
      "bodyEn": "No need to pad. 80–120 words is enough.",
      "task": "Email",
      "taskJp": "メール"
    },
    {
      "titleJp": "見直し・修正",
      "titleEn": "Review and revise",
      "bodyJp": "3ポイント全部入ってるか？スペルミスはないか？を最終確認",
      "bodyEn": "Check that all 3 points are in and there are no spelling errors.",
      "task": "Email",
      "taskJp": "メール"
    },
    {
      "titleJp": "主張",
      "titleEn": "Your claim",
      "bodyJp": "I believe that...質問に対して立場を明確に",
      "bodyEn": "I believe that...State your position on the question.",
      "task": "Discussion",
      "taskJp": "ディスカッション"
    },
    {
      "titleJp": "理由",
      "titleEn": "Reason",
      "bodyJp": "なぜその主張をするのか抽象的でなく具体的に",
      "bodyEn": "Why you hold that view.Be concrete, not abstract.",
      "task": "Discussion",
      "taskJp": "ディスカッション"
    },
    {
      "titleJp": "具体例",
      "titleEn": "Specific example",
      "bodyJp": "理由を裏付ける例を1つ1つだけ深く掘り下げる",
      "bodyEn": "One example that supports your reason.Develop just one in depth.",
      "task": "Discussion",
      "taskJp": "ディスカッション"
    },
    {
      "titleJp": "他の学生への言及",
      "titleEn": "Reference to other students",
      "bodyJp": "I agree with...Building on what X said...",
      "bodyEn": "I agree with...Building on what X said...",
      "task": "Discussion",
      "taskJp": "ディスカッション"
    }
  ],
  "speaking": [
    {
      "titleJp": "チャンクで記憶する",
      "titleEn": "",
      "bodyJp": "文全体を覚えようとせず、意味のかたまりで区切る。 例： \"The library offers / free workshops / on research skills / every Wednesday afternoon.\" → 4つのチャンクとして覚える",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "リズムとイントネーションをコピー",
      "titleEn": "",
      "bodyJp": "強弱とメロディーを真似る。単語を正確に言うだけでなく、英語らしいリズムで話すことが重要。 🔊 ネイティブの強弱パターンをそのままコピーする意識を持つ",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "録音開始後、2～3秒待つ",
      "titleEn": "",
      "bodyJp": "焦らず、最初の単語を噛みにくくなる。落ち着いて始めることで、全体の流れが良くなる。",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "間違えても止まらない",
      "titleEn": "",
      "bodyJp": "言い直して続ける方が高得点。止まると流暢性の評価が下がる。 ✗ 5秒以上の沈黙 → 大幅減点 ✓ 言い直して続ける → 軽微な減点のみ",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "🏋️ 自主練習の方法",
      "titleEn": "",
      "bodyJp": "Step 1: 各文を、チャンクごとに区切って音読する（ゆっくり） Step 2: チャンクを繋げて、文全体を通して音読する（自然なスピード） Step 3: スマホのタイマーを制限時間にセットし、音読する → 時間内に言い切れるか確認 Step 4: スマホの録音機能で自分の声を録音し、聞き返す → イントネーションやリズムをチェック 目標： 短い文がスムーズに言えるようになれば、本番でも十分対応できる。長い文は完璧でなくてもOK — 途中で止まらず最後まで言い切ることが最優先！",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "チャンクで記憶する：空港アナウンス編",
      "titleEn": "",
      "bodyJp": "空港の案内文は「指示」「場所」「条件」の3層構造でできていることが多い。チャンク単位で役割を意識すると覚えやすい。 例： \"If you have a connecting flight, / please proceed to the transfer desk / to confirm your next departure gate.\" → 条件 → 指示 → 目的の3パートに分解 例： \"Please make sure / all your carry-on luggage fits / in the overhead compartment / or under the seat in front of you.\" → 依頼 + 対象 + 場所A + 場所Bの4層構造で捉える",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "リズムコピー：空港アナウンストーンを再現",
      "titleEn": "",
      "bodyJp": "空港の案内放送は、落ち着いた丁寧なトーンと、重要語を強調するイントネーションが特徴。 例： \"I am afraid your flight has been delayed\" → \"afraid\" と \"delayed\" をやや強めに、申し訳なさそうなトーンで 例： \"We would like to inform all passengers\" → 丁寧でフォーマルなアナウンス調で 単語を正確に言うだけでなく、空港の案内にふさわしい落ち着いたトーンを意識する。",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "空港特有のリンキングポイント",
      "titleEn": "",
      "bodyJp": "空港フレーズでは、前置詞や関係詞のつながりが自然さを左右する。 \"has been delayed\" → has-been-delayed（3語を1つの流れで） \"overhead compartment\" → overhead-compartment（途切れずにつなげる） \"proceed to the\" → proceed-to-the（d→tのつながりを意識）",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "長文は「役割」で分けて覚える",
      "titleEn": "",
      "bodyJp": "24語の文も、役割ごとに分ければ覚えやすい。 Q7の例： ① 導入: \"We would like to inform all passengers\" ② 情報1: \"that complimentary Wi-Fi is available throughout the terminal,\" ③ 情報2: \"and charging stations can be found near every gate.\" → 導入→情報1→情報2の流れで自然に再生",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "チャンク記憶で長文を攻略",
      "titleEn": "",
      "bodyJp": "長い文を一語ずつ覚えようとすると短期記憶がパンクする。意味のかたまり（チャンク）で覚えることで、脳の負荷を大幅に減らせる。 例： \"Due to severe weather conditions, / all departures from this terminal / have been temporarily suspended / until further notice.\" → 16語でも4チャンクなら覚えられる！ 主語＋動詞をひとまとめにする 前置詞句（for / to / at / in...）を1チャンクにする カンマやピリオドの位置がチャンクの区切り目安",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "リズムコピーで自然さをアップ",
      "titleEn": "",
      "bodyJp": "単語を正確に言うだけでは不十分。ネイティブの強弱リズムをそのままコピーすることが高得点のカギ。 🔊 \"We aPOLogize for the deLAY and THANK you for your PAtience.\" → 大文字の部分を強く・長く発音。弱い部分は素早く通過する。 内容語（名詞・動詞・形容詞）は強く読む 機能語（冠詞・前置詞・代名詞）は弱く短く読む 音声を聞く時、メロディーとして捉える意識を持つ",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "聞き終わってから2秒待つ",
      "titleEn": "",
      "bodyJp": "音声が終わった瞬間に焦って話し始めると、最初の単語を噛みやすい。2秒間で文全体を頭の中で整理してから話し始める。 ⏱ 音声終了 → 1...2... → 自信を持ってスタート → 最初の単語がクリアだと、全体の印象が良くなる",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "録音開始後、2〜3秒待つ",
      "titleEn": "",
      "bodyJp": "焦らず、最初の単語を噛みにくくなる。落ち着いて始めることで、全体の流れが良くなる。",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "チャンクで記憶する：接客フレーズ編",
      "titleEn": "",
      "bodyJp": "接客英語は「決まり文句」が多いので、チャンクごとに覚えると効率的。 例： \"Please let me know / if you have / any food allergies / or dietary restrictions.\" → 接客定型表現 + 詳細情報の2層構造で捉える 例： \"We sincerely apologize / for the delay / and would like to offer you / a complimentary dessert.\" → 謝罪 + 理由 + 提案の3パートに分解",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "リズムコピー：接客トーンを再現",
      "titleEn": "",
      "bodyJp": "レストラン接客では、丁寧さと温かさを伝えるイントネーションが重要。 🔊 \"May I take your order?\" → やわらかく上昇する調子で丁寧に 🔊 \"We sincerely apologize\" → ゆっくりと誠意を込めたトーンで 単語を正確に言うだけでなく、接客にふさわしい温かいトーンを意識する。",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "レストラン特有のリンキングポイント",
      "titleEn": "",
      "bodyJp": "接客フレーズでは、単語のつながり（リンキング）が自然さを左右する。 \"would like to offer\" → would-like-to-offer（4語を1つの流れで） \"grilled salmon with\" → grilled-salmon-with（途切れずにつなげる） \"enjoyed your dining\" → enjoyed-your-dining（d→yのつながりを意識）",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "リズムとイントネーションをコピーする",
      "titleEn": "",
      "bodyJp": "強弱とメロディーを真似る。単語を正確に言うだけでなく、英語らしいリズムで話すことが重要。 ポイント： ネイティブの強弱パターンをそのままコピーする意識を持つ",
      "bodyEn": "",
      "task": "Listen & Repeat",
      "taskJp": "Listen & Repeat"
    },
    {
      "titleJp": "45秒の使い方",
      "titleEn": "",
      "bodyJp": "時間配分を決めておくと、沈黙を避けて内容を詰め込める。 主張 5秒 理由 15秒 具体例 15秒 まとめ 10秒",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "沈黙を避けるフレーズ",
      "titleEn": "",
      "bodyJp": "困ったときに使えるフレーズを事前に準備しておく。 考え中 Let me think about that... 始める Well, in my opinion... 例を出す For instance... まとめ So overall...",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "失敗パターンとリカバリー",
      "titleEn": "",
      "bodyJp": "✗ NG： 5秒以上の沈黙 ✓ OK： → \"Well, let me think...\" でつなぐ ✗ NG： 理由が2つで中途半端 ✓ OK： → 1つに絞って深く説明する ✗ NG： 同語反復（同じ言葉を繰り返す） ✓ OK： → \"What I mean by that is...\" で言い換える ✗ NG： 途中で止まる ✓ OK： → 間違えても続ける。流暢性が重要",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "★ 使い回せる具体例ストック",
      "titleEn": "",
      "bodyJp": "どんなトピックでも使えるエピソードを5つ準備しておく。 📚 学校の課題 🙋 友人エピソード 🚙 家族との旅行 ⚽ 部活・クラブ 💻 テクノロジー",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "🏋️ 自主練習の方法",
      "titleEn": "",
      "bodyJp": "Step 1: スマホのタイマーを45秒にセットする Step 2: 質問を声に出して読む（本番では音声で流れる部分） Step 3: 読み終わったらすぐタイマースタート → 45秒以内に「主張→理由→具体例→まとめ」を言い切る Step 4: 録音して聞き返す → 沈黙がないか、まとめまで到達しているかチェック 💡 本番では質問は音声のみ（画面にテキストは表示されません）。聞いた瞬間に回答を組み立てる練習が重要！ 目標： 1日2〜3回のルーティンを体に覚えさせる。完璧な英語でなくてOK — 止まらず話し続けることが最優先！",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "45秒の使い方（旅行トピック向け）",
      "titleEn": "",
      "bodyJp": "旅行トピックはエピソードが話しやすいので、具体例に時間を多めに取る。 主張 5秒 理由 10秒 具体例 20秒 まとめ 10秒",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "理由は「1つ深く」が鉄則",
      "titleEn": "",
      "bodyJp": "理由を2つ挙げようとすると、どちらも中途半端になりがち。1つの理由を深く掘り下げて、具体例まで到達するのが高得点パターン。 ✗ NG： 訪問地を列挙するだけ ✓ OK： 1つの旅行に絞って深く説明する",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "★ 旅行トピックで使える具体例ストック",
      "titleEn": "",
      "bodyJp": "どんな質問にも応用できるエピソードを準備しておく。 🚗 家族旅行 ✈️ 海外旅行 🏔️ 自然体験 🏛️ 文化体験 ✈ 空港でのトラブル",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "45秒の時間配分",
      "titleEn": "",
      "bodyJp": "45秒は短いようで、テンプレートに沿えば十分な内容を詰め込める。時間配分を体に覚えさせることが重要。 主張 5秒 理由 15秒 具体例 15秒 まとめ 10秒",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "Health テーマで使えるフレーズ",
      "titleEn": "",
      "bodyJp": "健康・フィットネスの話題で頻出するフレーズを事前に準備しておく。 運動の習慣 I try to exercise regularly... 健康の重要性 Health is one of the most important things... 生活習慣 In terms of my daily routine... 意見を述べる From my perspective...",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "よくある失敗パターンと対策",
      "titleEn": "",
      "bodyJp": "✗ NG： 具体例なしで抽象的に話し続ける ✓ OK： → \"For example, last month I started jogging...\" のように自分の体験を入れる ✗ NG： 理由を2つ挙げて両方中途半端 ✓ OK： → 理由は1つに絞り、具体例で深く掘り下げる ✗ NG： 時間が余って沈黙で終わる ✓ OK： → まとめで「That's why I strongly believe...」と繰り返して時間を使い切る ✗ NG： 難しい単語を使おうとして詰まる ✓ OK： → シンプルな単語で流暢に話す方が高得点",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "食べ物トピックで使えるフィラーフレーズ",
      "titleEn": "",
      "bodyJp": "困ったときに時間を稼ぐフレーズを準備しておく。 考え中 That's an interesting question... 体験を思い出す If I remember correctly... 例を出す A good example would be... 言い換え What I mean by that is... 追加情報 On top of that... まとめ All things considered...",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "★ 食べ物トピックで使える具体例ストック",
      "titleEn": "",
      "bodyJp": "どんな質問にも応用できるエピソードを準備しておく。 🍲 家族との食事 🍳 初めての料理 🍝 海外で食べたもの 🍰 好きなレシピ 🍛 地元の名物料理",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "45秒の構成：主張→理由→具体例→まとめ",
      "titleEn": "",
      "bodyJp": "45秒を以下のように配分する。全パートを言い切ることが最重要。 主張 5秒 理由 15秒 具体例 15秒 まとめ 10秒",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    },
    {
      "titleJp": "万能テンプレート",
      "titleEn": "",
      "bodyJp": "この4ステップを覚えれば、どんな質問にも対応できる。",
      "bodyEn": "",
      "task": "Take an Interview",
      "taskJp": "インタビュー"
    }
  ]
};
